[package]
name = "cli"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "Awesome Schema CLI."

[lib]
path = "src/lib.rs"

[[bin]]
name = "awesome-schema"
path = "src/main.rs"

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
schema-core.workspace = true
parser.workspace = true
migrations.workspace = true
renderers.workspace = true
codegen-rust.workspace = true
codegen-typescript.workspace = true
serde_json.workspace = true
surrealdb.workspace = true
tokio.workspace = true

[dev-dependencies]
tempfile.workspace = true
assert_cmd.workspace = true
predicates.workspace = true
schema-core.workspace = true
