use codegen::CodeGenerator;
use core::usecases::CodeGeneratorPort;
use core::{DatabaseSchema, DomainError};

pub struct RustGenerator;

impl RustGenerator {
    #[must_use]
    pub const fn new() -> Self {
        Self
    }
}

impl Default for RustGenerator {
    fn default() -> Self {
        Self::new()
    }
}

impl CodeGenerator for RustGenerator {
    fn language(&self) -> &'static str {
        "rust"
    }

    fn generate(&self, schema: &DatabaseSchema) -> Result<String, DomainError> {
        let mut lines = vec![
            "// Generated by Awesome Schema".to_owned(),
            "// Rust model generation stub — expand in future milestones".to_owned(),
            String::new(),
        ];

        for model in &schema.models {
            lines.push(format!("pub struct {} {{", model.name));
            for field in &model.fields {
                let rust_type = map_field_type(&field.field_type);
                let optional = if field.optional { "Option<" } else { "" };
                let optional_close = if field.optional { ">" } else { "" };
                lines.push(format!(
                    "    pub {}: {optional}{rust_type}{optional_close},",
                    field.name
                ));
            }
            lines.push("}".to_owned());
            lines.push(String::new());
        }

        Ok(lines.join("\n"))
    }
}

impl CodeGeneratorPort for RustGenerator {
    fn generate(&self, schema: &DatabaseSchema) -> Result<String, DomainError> {
        CodeGenerator::generate(self, schema)
    }
}

fn map_field_type(field_type: &core::FieldType) -> String {
    match field_type {
        core::FieldType::Int => "i64".to_owned(),
        core::FieldType::Float => "f64".to_owned(),
        core::FieldType::Bool => "bool".to_owned(),
        core::FieldType::Datetime => "chrono::DateTime<chrono::Utc>".to_owned(),
        core::FieldType::Object => "serde_json::Value".to_owned(),
        core::FieldType::Array(inner) => format!("Vec<{}>", map_field_type(inner)),
        core::FieldType::String | core::FieldType::RecordId(_) | core::FieldType::Model(_) => {
            "String".to_owned()
        }
        core::FieldType::Custom(value) => value.clone(),
    }
}
