[package]
name = "codegen-rust"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "Rust model code generation."

[lints]
workspace = true

[dependencies]
codegen.workspace = true
core.workspace = true

[dev-dependencies]
codegen.workspace = true
