[package]
name = "renderers"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "Database-specific schema and migration renderers."

[lints]
workspace = true

[dependencies]
core.workspace = true

[dev-dependencies]
core.workspace = true
