#![allow(clippy::missing_errors_doc, clippy::too_many_lines)]

use codegen::CodeGenerator;
use core::usecases::CodeGeneratorPort;
use core::{
    DatabaseSchema, DomainError, Edge, Field, FieldType, Model, NamingContext, ObjectTypeDefinition,
};

pub struct TypeScriptGenerator;

impl TypeScriptGenerator {
    #[must_use]
    pub const fn new() -> Self {
        Self
    }
}

impl Default for TypeScriptGenerator {
    fn default() -> Self {
        Self::new()
    }
}

impl CodeGenerator for TypeScriptGenerator {
    fn language(&self) -> &'static str {
        "typescript"
    }

    fn generate(&self, schema: &DatabaseSchema) -> Result<String, DomainError> {
        Ok(emit_typescript(schema))
    }
}

impl CodeGeneratorPort for TypeScriptGenerator {
    fn generate(&self, schema: &DatabaseSchema) -> Result<String, DomainError> {
        CodeGenerator::generate(self, schema)
    }
}

fn emit_typescript(schema: &DatabaseSchema) -> String {
    let naming = NamingContext::new(&schema.naming, &schema.models);
    let mut out = vec![
        "// Generated by Awesome Schema".to_owned(),
        "// Requires a SurrealDB JS client compatible with SurrealLike (e.g. `surrealdb`).".to_owned(),
        "// Prefer `recordId(Tables.User, key)` for branded ids.".to_owned(),
        String::new(),
        "/** Surreal record id branded by table name. */".to_owned(),
        "export type RecordId<Table extends string = string> =".to_owned(),
        "  string & { readonly __table?: Table };".to_owned(),
        String::new(),
    ];

    for object_type in &schema.object_types {
        emit_object_type(&mut out, object_type, &naming);
    }

    for model in &schema.models {
        emit_model_record(&mut out, schema, model, &naming);
        emit_model_selected(&mut out, schema, model, &naming);
        emit_model_inputs(&mut out, schema, model, &naming);
    }

    for edge in &schema.edges {
        emit_edge_record(&mut out, schema, edge, &naming);
        emit_edge_selected(&mut out, schema, edge, &naming);
        emit_edge_inputs(&mut out, schema, edge, &naming);
    }

    emit_select_type_utils(&mut out);
    for model in &schema.models {
        emit_model_select_payload(&mut out, schema, model, &naming);
    }
    for edge in &schema.edges {
        emit_edge_select_payload(&mut out, schema, edge, &naming);
    }

    emit_tables_const(&mut out, schema, &naming);
    emit_select_meta_registry(&mut out, schema, &naming);
    emit_record_id_helpers(&mut out);
    emit_surreal_like(&mut out);
    emit_shared_runtime(&mut out);
    emit_select_helpers(&mut out, schema, &naming);
    emit_crud_helpers(&mut out, schema, &naming);
    emit_query_helpers(&mut out, schema, &naming);
    emit_fluent_client(&mut out, schema, &naming);

    out.join("\n")
}

fn emit_object_type(out: &mut Vec<String>, object_type: &ObjectTypeDefinition, naming: &NamingContext<'_>) {
    out.push(format!("export type {} = {{", object_type.name));
    for field in &object_type.fields {
        let ts = map_object_field_type(&field.field_type, naming);
        let optional = if field.optional { "?" } else { "" };
        out.push(format!("  {}{optional}: {};", field.name, ts));
    }
    if object_type.flexible {
        out.push("  [key: string]: unknown;".to_owned());
    }
    out.push("};".to_owned());
    out.push(String::new());
}

fn emit_model_record(
    out: &mut Vec<String>,
    schema: &DatabaseSchema,
    model: &Model,
    naming: &NamingContext<'_>,
) {
    out.push(format!("export type {} = {{", model.name));
    for field in model.fields.iter().filter(|f| !f.name.contains('.')) {
        if should_omit_on_record(field) {
            continue;
        }
        let ts = map_model_field_record(schema, model, field, naming);
        let optional = if field.optional { "?" } else { "" };
        let name = naming.field_name(field);
        out.push(format!("  {name}{optional}: {ts};"));
    }
    out.push("};".to_owned());
    out.push(String::new());
}

fn emit_model_selected(
    out: &mut Vec<String>,
    schema: &DatabaseSchema,
    model: &Model,
    naming: &NamingContext<'_>,
) {
    out.push(format!("export type {}Selected = {{", model.name));
    for field in model.fields.iter().filter(|f| !f.name.contains('.')) {
        let ts = map_model_field_selected(schema, model, field, naming);
        let optional = if field.optional || field.is_computed_link() || field.relation_name.is_some()
        {
            "?"
        } else {
            ""
        };
        let name = naming.field_name(field);
        out.push(format!("  {name}{optional}: {ts};"));
    }
    out.push("};".to_owned());
    out.push(String::new());
}

fn emit_model_inputs(
    out: &mut Vec<String>,
    schema: &DatabaseSchema,
    model: &Model,
    naming: &NamingContext<'_>,
) {
    out.push(format!("export type {}CreateInput = {{", model.name));
    for field in model.fields.iter().filter(|f| !f.name.contains('.')) {
        if field.is_id || should_omit_on_record(field) {
            continue;
        }
        let ts = map_model_field_record(schema, model, field, naming);
        let optional = if field.optional { "?" } else { "" };
        let name = naming.field_name(field);
        out.push(format!("  {name}{optional}: {ts};"));
    }
    out.push("};".to_owned());
    out.push(String::new());

    out.push(format!("export type {}UpdateInput = {{", model.name));
    for field in model.fields.iter().filter(|f| !f.name.contains('.')) {
        if field.is_id || should_omit_on_record(field) {
            continue;
        }
        let ts = map_model_field_record(schema, model, field, naming);
        let name = naming.field_name(field);
        out.push(format!("  {name}?: {ts};"));
    }
    out.push("};".to_owned());
    out.push(String::new());
}

fn emit_select_type_utils(out: &mut Vec<String>) {
    out.push("/** `true` or nested `{ select }` for a related entity. */".to_owned());
    out.push("export type SelectArg<S> = boolean | { select?: S };".to_owned());
    out.push(String::new());
    out.push(
        "/** Resolve one select entry: `true` → Default; `{ select: N }` → nested payload. */"
            .to_owned(),
    );
    out.push("export type ResolveSelectField<".to_owned());
    out.push("  V,".to_owned());
    out.push("  Default,".to_owned());
    out.push("  NestedSelect,".to_owned());
    out.push("  NestedPayload,".to_owned());
    out.push("> = V extends true".to_owned());
    out.push("  ? Default".to_owned());
    out.push("  : V extends { select?: NestedSelect }".to_owned());
    out.push("    ? NestedPayload".to_owned());
    out.push("    : never;".to_owned());
    out.push(String::new());
}

fn emit_model_select_payload(
    out: &mut Vec<String>,
    schema: &DatabaseSchema,
    model: &Model,
    naming: &NamingContext<'_>,
) {
    let fields: Vec<&Field> = model
        .fields
        .iter()
        .filter(|field| !field.name.contains('.'))
        .filter(|field| {
            !should_omit_on_record(field) || field.is_link() || field.relation_name.is_some()
        })
        .collect();

    out.push(format!("export type {}Scalars = {{", model.name));
    for field in &fields {
        if field.is_link() || field.relation_name.is_some() {
            continue;
        }
        let name = naming.field_name(field);
        let ts = map_model_field_record(schema, model, field, naming);
        out.push(format!("  {name}: {ts};"));
    }
    out.push("};".to_owned());
    out.push(String::new());

    out.push(format!("export type {}Select = {{", model.name));
    for field in &fields {
        let name = naming.field_name(field);
        if field.is_link() || field.relation_name.is_some() {
            let target_select = relation_select_type_name(schema, field);
            out.push(format!("  {name}?: SelectArg<{target_select}>;"));
        } else {
            out.push(format!("  {name}?: boolean;"));
        }
    }
    out.push("};".to_owned());
    out.push(String::new());

    for field in fields.iter().filter(|f| f.is_link() || f.relation_name.is_some()) {
        let name = naming.field_name(field);
        let alias = format!("{}{}Field", model.name, pascal_case(&name));
        let (default_ty, nested_select, list) = relation_payload_parts(schema, field);
        let default = if list {
            format!("{default_ty}[]")
        } else {
            default_ty.clone()
        };
        let nested_payload = if list {
            format!("{default_ty}GetPayload<N>[]")
        } else {
            format!("{default_ty}GetPayload<N>")
        };
        out.push(format!("type {alias}<V> = V extends true"));
        out.push(format!("  ? {default}"));
        out.push(format!(
            "  : V extends {{ select?: infer N extends {nested_select} | undefined }}"
        ));
        out.push(format!("    ? {nested_payload}"));
        out.push("    : never;".to_owned());
        out.push(String::new());
    }

    out.push(format!(
        "export type {}GetPayload<S extends {}Select | undefined = undefined> =",
        model.name, model.name
    ));
    out.push("  [S] extends [undefined]".to_owned());
    out.push(format!("    ? {}", model.name));
    out.push("    : {".to_owned());
    out.push(
        "        [K in keyof S as S[K] extends false | undefined ? never : K]-?:"
            .to_owned(),
    );
    out.push(format!("          K extends keyof {}Scalars", model.name));
    out.push(format!("            ? {}Scalars[K]", model.name));
    for field in fields.iter().filter(|f| f.is_link() || f.relation_name.is_some()) {
        let name = naming.field_name(field);
        let alias = format!("{}{}Field", model.name, pascal_case(&name));
        out.push(format!("            : K extends \"{name}\""));
        out.push(format!("              ? {alias}<S[K]>"));
    }
    out.push("            : never;".to_owned());
    out.push("      };".to_owned());
    out.push(String::new());
}

fn emit_edge_record(
    out: &mut Vec<String>,
    schema: &DatabaseSchema,
    edge: &Edge,
    naming: &NamingContext<'_>,
) {
    let in_table = table_for_model_name(schema, &edge.in_model, naming);
    let out_table = table_for_model_name(schema, &edge.out_model, naming);
    out.push(format!("export type {} = {{", edge.name));
    out.push(format!("  id: RecordId<\"{}\">;", edge.table_name(naming.convention())));
    out.push(format!("  in: RecordId<\"{in_table}\">;"));
    out.push(format!("  out: RecordId<\"{out_table}\">;"));
    for field in edge.fields.iter().filter(|f| !f.name.contains('.')) {
        let ts = map_scalar_or_object(None, &field.field_type, field, naming);
        let optional = if field.optional { "?" } else { "" };
        let name = naming.field_name(field);
        out.push(format!("  {name}{optional}: {ts};"));
    }
    out.push("};".to_owned());
    out.push(String::new());
}

fn emit_edge_selected(
    out: &mut Vec<String>,
    _schema: &DatabaseSchema,
    edge: &Edge,
    naming: &NamingContext<'_>,
) {
    out.push(format!("export type {}Selected = {{", edge.name));
    out.push(format!("  id: RecordId<\"{}\">;", edge.table_name(naming.convention())));
    out.push(format!("  in: {}Selected;", edge.in_model));
    out.push(format!("  out: {}Selected;", edge.out_model));
    for field in edge.fields.iter().filter(|f| !f.name.contains('.')) {
        let ts = map_scalar_or_object(None, &field.field_type, field, naming);
        let optional = if field.optional { "?" } else { "" };
        let name = naming.field_name(field);
        out.push(format!("  {name}{optional}: {ts};"));
    }
    out.push("};".to_owned());
    out.push(String::new());
}

fn emit_edge_inputs(
    out: &mut Vec<String>,
    schema: &DatabaseSchema,
    edge: &Edge,
    naming: &NamingContext<'_>,
) {
    let in_table = table_for_model_name(schema, &edge.in_model, naming);
    let out_table = table_for_model_name(schema, &edge.out_model, naming);
    out.push(format!("export type {}CreateInput = {{", edge.name));
    out.push(format!("  in: RecordId<\"{in_table}\"> | string;"));
    out.push(format!("  out: RecordId<\"{out_table}\"> | string;"));
    for field in edge.fields.iter().filter(|f| !f.name.contains('.')) {
        let ts = map_scalar_or_object(None, &field.field_type, field, naming);
        let optional = if field.optional { "?" } else { "" };
        let name = naming.field_name(field);
        out.push(format!("  {name}{optional}: {ts};"));
    }
    out.push("};".to_owned());
    out.push(String::new());

    out.push(format!("export type {}UpdateInput = {{", edge.name));
    out.push(format!("  in?: RecordId<\"{in_table}\"> | string;"));
    out.push(format!("  out?: RecordId<\"{out_table}\"> | string;"));
    for field in edge.fields.iter().filter(|f| !f.name.contains('.')) {
        let ts = map_scalar_or_object(None, &field.field_type, field, naming);
        let name = naming.field_name(field);
        out.push(format!("  {name}?: {ts};"));
    }
    out.push("};".to_owned());
    out.push(String::new());
}

fn emit_edge_select_payload(
    out: &mut Vec<String>,
    schema: &DatabaseSchema,
    edge: &Edge,
    naming: &NamingContext<'_>,
) {
    let in_table = table_for_model_name(schema, &edge.in_model, naming);
    let out_table = table_for_model_name(schema, &edge.out_model, naming);

    out.push(format!("export type {}Scalars = {{", edge.name));
    out.push(format!(
        "  id: RecordId<\"{}\">;",
        edge.table_name(naming.convention())
    ));
    out.push(format!("  in: RecordId<\"{in_table}\">;"));
    out.push(format!("  out: RecordId<\"{out_table}\">;"));
    for field in edge.fields.iter().filter(|f| !f.name.contains('.')) {
        let name = naming.field_name(field);
        let ts = map_scalar_or_object(None, &field.field_type, field, naming);
        out.push(format!("  {name}: {ts};"));
    }
    out.push("};".to_owned());
    out.push(String::new());

    out.push(format!("export type {}Select = {{", edge.name));
    out.push("  id?: boolean;".to_owned());
    out.push(format!("  in?: SelectArg<{}Select>;", edge.in_model));
    out.push(format!("  out?: SelectArg<{}Select>;", edge.out_model));
    for field in edge.fields.iter().filter(|f| !f.name.contains('.')) {
        let name = naming.field_name(field);
        out.push(format!("  {name}?: boolean;"));
    }
    out.push("};".to_owned());
    out.push(String::new());

    out.push(format!("type {}InField<V> = V extends true", edge.name));
    out.push(format!("  ? {}", edge.in_model));
    out.push(format!(
        "  : V extends {{ select?: infer N extends {}Select | undefined }}",
        edge.in_model
    ));
    out.push(format!("    ? {}GetPayload<N>", edge.in_model));
    out.push("    : never;".to_owned());
    out.push(String::new());

    out.push(format!("type {}OutField<V> = V extends true", edge.name));
    out.push(format!("  ? {}", edge.out_model));
    out.push(format!(
        "  : V extends {{ select?: infer N extends {}Select | undefined }}",
        edge.out_model
    ));
    out.push(format!("    ? {}GetPayload<N>", edge.out_model));
    out.push("    : never;".to_owned());
    out.push(String::new());

    out.push(format!(
        "export type {}GetPayload<S extends {}Select | undefined = undefined> =",
        edge.name, edge.name
    ));
    out.push("  [S] extends [undefined]".to_owned());
    out.push(format!("    ? {}", edge.name));
    out.push("    : {".to_owned());
    out.push(
        "        [K in keyof S as S[K] extends false | undefined ? never : K]-?:"
            .to_owned(),
    );
    out.push(format!("          K extends \"in\" ? {}InField<S[K]>", edge.name));
    out.push(format!("          : K extends \"out\" ? {}OutField<S[K]>", edge.name));
    out.push(format!("          : K extends keyof {}Scalars ? {}Scalars[K]", edge.name, edge.name));
    out.push("          : never;".to_owned());
    out.push("      };".to_owned());
    out.push(String::new());
}

fn relation_select_type_name(schema: &DatabaseSchema, field: &Field) -> String {
    if let Some(relation) = &field.relation_name {
        return format!("{}Select", resolve_edge_type_name(schema, relation));
    }
    let target = field
        .link_target
        .as_deref()
        .or_else(|| field.field_type.link_model_name())
        .unwrap_or("unknown");
    format!("{target}Select")
}

fn relation_payload_parts(schema: &DatabaseSchema, field: &Field) -> (String, String, bool) {
    let list = field.is_list_link() || matches!(field.field_type, FieldType::Array(_));
    if let Some(relation) = &field.relation_name {
        let edge = resolve_edge_type_name(schema, relation);
        return (edge.clone(), format!("{edge}Select"), list);
    }
    let target = field
        .link_target
        .as_deref()
        .or_else(|| field.field_type.link_model_name())
        .unwrap_or("unknown")
        .to_owned();
    (target.clone(), format!("{target}Select"), list)
}

fn pascal_case(name: &str) -> String {
    let mut chars = name.chars();
    chars.next().map_or_else(String::new, |first| {
        first.to_uppercase().collect::<String>() + chars.as_str()
    })
}

fn should_omit_on_record(field: &Field) -> bool {
    field.is_computed_link() || field.relation_name.is_some()
}

fn map_model_field_record(
    schema: &DatabaseSchema,
    model: &Model,
    field: &Field,
    naming: &NamingContext<'_>,
) -> String {
    if field.is_id {
        if let Some(model_name) = field.field_type.link_model_name() {
            let table = table_for_model_name(schema, model_name, naming);
            return format!("RecordId<\"{table}\">");
        }
        if let FieldType::RecordId(target) = &field.field_type {
            let table = table_for_model_name(schema, target, naming);
            return format!("RecordId<\"{table}\">");
        }
    }

    if field.is_stored_link() {
        return map_link_as_record_id(schema, field, naming);
    }

    map_scalar_or_object(Some((schema, model)), &field.field_type, field, naming)
}

fn map_model_field_selected(
    schema: &DatabaseSchema,
    model: &Model,
    field: &Field,
    naming: &NamingContext<'_>,
) -> String {
    if field.is_id {
        return map_model_field_record(schema, model, field, naming);
    }

    if let Some(relation) = &field.relation_name {
        let edge_name = resolve_edge_type_name(schema, relation);
        let list = field.is_list_link() || matches!(field.field_type, FieldType::Array(_));
        return if list {
            format!("{edge_name}Selected[]")
        } else {
            format!("{edge_name}Selected")
        };
    }

    if field.is_link() {
        let target = field
            .link_target
            .as_deref()
            .or_else(|| field.field_type.link_model_name())
            .unwrap_or("unknown");
        let list = field.is_list_link();
        return if list {
            format!("{target}Selected[]")
        } else {
            format!("{target}Selected")
        };
    }

    map_scalar_or_object(Some((schema, model)), &field.field_type, field, naming)
}

fn map_link_as_record_id(schema: &DatabaseSchema, field: &Field, naming: &NamingContext<'_>) -> String {
    let target = field
        .link_target
        .as_deref()
        .or_else(|| field.field_type.link_model_name())
        .unwrap_or("unknown");
    let table = table_for_model_name(schema, target, naming);
    if field.is_list_link() {
        format!("RecordId<\"{table}\">[]")
    } else {
        format!("RecordId<\"{table}\">")
    }
}

fn map_scalar_or_object(
    ctx: Option<(&DatabaseSchema, &Model)>,
    field_type: &FieldType,
    field: &Field,
    naming: &NamingContext<'_>,
) -> String {
    match field_type {
        FieldType::Object => {
            if let Some((schema, model)) = ctx
                && let Some(name) = resolve_named_object_type(schema, model, field)
            {
                return name;
            }
            "Record<string, unknown>".to_owned()
        }
        FieldType::Model(name) if field.link_target.is_none() && field.relation_name.is_none() => {
            name.clone()
        }
        other => map_object_field_type(other, naming),
    }
}

fn resolve_named_object_type(
    schema: &DatabaseSchema,
    model: &Model,
    parent: &Field,
) -> Option<String> {
    let prefix = format!("{}.", parent.name);
    let nested: Vec<&Field> = model
        .fields
        .iter()
        .filter(|field| field.name.starts_with(&prefix))
        .collect();

    schema.object_types.iter().find_map(|object_type| {
        if object_type.flexible != parent.flexible {
            return None;
        }
        if object_type.fields.len() != nested.len() {
            return None;
        }
        let matched = object_type.fields.iter().all(|candidate| {
            nested.iter().any(|field| {
                field.name == format!("{}.{}", parent.name, candidate.name)
                    && field.field_type == candidate.field_type
                    && field.optional == candidate.optional
            })
        });
        matched.then(|| object_type.name.clone())
    })
}

fn map_object_field_type(field_type: &FieldType, naming: &NamingContext<'_>) -> String {
    match field_type {
        FieldType::String => "string".to_owned(),
        FieldType::Int | FieldType::Float => "number".to_owned(),
        FieldType::Bool => "boolean".to_owned(),
        FieldType::Datetime => "Date".to_owned(),
        FieldType::Object => "Record<string, unknown>".to_owned(),
        FieldType::Array(inner) => format!("{}[]", map_object_field_type(inner, naming)),
        FieldType::RecordId(name) => {
            let table = naming.convention().tables.apply(name);
            format!("RecordId<\"{table}\">")
        }
        FieldType::Model(name) => name.clone(),
        FieldType::Custom(value) => value.clone(),
    }
}

fn table_for_model_name(schema: &DatabaseSchema, model_name: &str, naming: &NamingContext<'_>) -> String {
    schema
        .models
        .iter()
        .find(|model| model.name == model_name)
        .map_or_else(
            || naming.convention().tables.apply(model_name),
            |model| model.table_name(naming.convention()),
        )
}

fn resolve_edge_type_name(schema: &DatabaseSchema, relation_name: &str) -> String {
    schema
        .edges
        .iter()
        .find(|edge| {
            edge.name == relation_name
                || edge.table_name(&schema.naming) == *relation_name
                || edge.attributes.get("map").is_some_and(|mapped| mapped == relation_name)
        })
        .map_or_else(|| relation_name.to_owned(), |edge| edge.name.clone())
}

fn client_key(name: &str) -> String {
    let mut chars = name.chars();
    chars.next().map_or_else(String::new, |first| {
        first.to_lowercase().collect::<String>() + chars.as_str()
    })
}

fn query_fn_name(name: &str) -> String {
    if name.ends_with('s') {
        format!("query{name}")
    } else {
        format!("query{name}s")
    }
}

fn query_related_fn_name(name: &str) -> String {
    format!("{}Related", query_fn_name(name))
}

fn emit_tables_const(out: &mut Vec<String>, schema: &DatabaseSchema, naming: &NamingContext<'_>) {
    out.push("export const Tables = {".to_owned());
    for model in &schema.models {
        out.push(format!(
            "  {}: \"{}\",",
            model.name,
            model.table_name(naming.convention())
        ));
    }
    for edge in &schema.edges {
        out.push(format!(
            "  {}: \"{}\",",
            edge.name,
            edge.table_name(naming.convention())
        ));
    }
    out.push("} as const;".to_owned());
    out.push(String::new());
}

fn emit_select_meta_registry(
    out: &mut Vec<String>,
    schema: &DatabaseSchema,
    naming: &NamingContext<'_>,
) {
    out.push("export type FieldSelectMeta =".to_owned());
    out.push("  | { kind: \"scalar\" }".to_owned());
    out.push(
        "  | { kind: \"stored\" | \"computed\"; targetTable: string; list: boolean }".to_owned(),
    );
    out.push(
        "  | { kind: \"edge\"; edgeTable: string; dir: \"out\" | \"in\"; list: boolean };"
            .to_owned(),
    );
    out.push(String::new());
    out.push(
        "export const SelectMetaByTable: Record<string, Record<string, FieldSelectMeta>> = {"
            .to_owned(),
    );

    for model in &schema.models {
        let table = model.table_name(naming.convention());
        out.push(format!("  \"{table}\": {{"));
        for field in model.fields.iter().filter(|f| !f.name.contains('.')) {
            let name = naming.field_name(field);
            if let Some(relation) = &field.relation_name {
                let edge_name = resolve_edge_type_name(schema, relation);
                let Some(edge) = schema.edges.iter().find(|e| e.name == edge_name) else {
                    continue;
                };
                let edge_table = edge.table_name(naming.convention());
                let dir = if edge.in_model == model.name {
                    "out"
                } else if edge.out_model == model.name {
                    "in"
                } else {
                    continue;
                };
                let list = field.is_list_link()
                    || matches!(field.field_type, FieldType::Array(_));
                out.push(format!(
                    "    {name}: {{ kind: \"edge\", edgeTable: \"{edge_table}\", dir: \"{dir}\", list: {list} }},"
                ));
            } else if field.is_link() {
                let target = field
                    .link_target
                    .as_deref()
                    .or_else(|| field.field_type.link_model_name())
                    .unwrap_or("unknown");
                let target_table = table_for_model_name(schema, target, naming);
                let kind = if field.is_computed_link() {
                    "computed"
                } else {
                    "stored"
                };
                let list = field.is_list_link();
                out.push(format!(
                    "    {name}: {{ kind: \"{kind}\", targetTable: \"{target_table}\", list: {list} }},"
                ));
            } else if !should_omit_on_record(field) {
                out.push(format!("    {name}: {{ kind: \"scalar\" }},"));
            }
        }
        out.push("  },".to_owned());
    }

    for edge in &schema.edges {
        let table = edge.table_name(naming.convention());
        let in_table = table_for_model_name(schema, &edge.in_model, naming);
        let out_table = table_for_model_name(schema, &edge.out_model, naming);
        out.push(format!("  \"{table}\": {{"));
        out.push("    id: { kind: \"scalar\" },".to_owned());
        out.push(format!(
            "    in: {{ kind: \"stored\", targetTable: \"{in_table}\", list: false }},"
        ));
        out.push(format!(
            "    out: {{ kind: \"stored\", targetTable: \"{out_table}\", list: false }},"
        ));
        for field in edge.fields.iter().filter(|f| !f.name.contains('.')) {
            let name = naming.field_name(field);
            out.push(format!("    {name}: {{ kind: \"scalar\" }},"));
        }
        out.push("  },".to_owned());
    }

    out.push("};".to_owned());
    out.push(String::new());
}

fn emit_record_id_helpers(out: &mut Vec<String>) {
    out.push("export function recordId<Table extends string>(".to_owned());
    out.push("  table: Table,".to_owned());
    out.push("  key: string,".to_owned());
    out.push("): RecordId<Table> {".to_owned());
    out.push("  return `${table}:${key}` as RecordId<Table>;".to_owned());
    out.push("}".to_owned());
    out.push(String::new());
    out.push("export function parseRecordId(".to_owned());
    out.push("  value: string,".to_owned());
    out.push("): { table: string; key: string } | null {".to_owned());
    out.push("  const i = value.indexOf(\":\");".to_owned());
    out.push("  if (i <= 0) return null;".to_owned());
    out.push("  return { table: value.slice(0, i), key: value.slice(i + 1) };".to_owned());
    out.push("}".to_owned());
    out.push(String::new());
    out.push("export function asRecordId<Table extends string>(".to_owned());
    out.push("  table: Table,".to_owned());
    out.push("  value: string,".to_owned());
    out.push("): RecordId<Table> {".to_owned());
    out.push("  return (value.includes(\":\") ? value : `${table}:${value}`) as RecordId<Table>;".to_owned());
    out.push("}".to_owned());
    out.push(String::new());
    out.push("function normalizeThing(table: string, id: string): string {".to_owned());
    out.push("  return id.includes(\":\") ? id : `${table}:${id}`;".to_owned());
    out.push("}".to_owned());
    out.push(String::new());
    out.push("async function firstRow<T>(result: unknown): Promise<T | undefined> {".to_owned());
    out.push("  if (Array.isArray(result)) {".to_owned());
    out.push("    const first = result[0];".to_owned());
    out.push("    if (Array.isArray(first)) return first[0] as T | undefined;".to_owned());
    out.push("    return first as T | undefined;".to_owned());
    out.push("  }".to_owned());
    out.push("  return result as T | undefined;".to_owned());
    out.push("}".to_owned());
    out.push(String::new());
    out.push("async function asRows<T>(result: unknown): Promise<T[]> {".to_owned());
    out.push("  if (Array.isArray(result)) {".to_owned());
    out.push("    const first = result[0];".to_owned());
    out.push("    if (Array.isArray(first)) return first as T[];".to_owned());
    out.push("    return result as T[];".to_owned());
    out.push("  }".to_owned());
    out.push("  if (result == null) return [];".to_owned());
    out.push("  return [result as T];".to_owned());
    out.push("}".to_owned());
    out.push(String::new());
    out.push("function selectedFetchKeys(select: Record<string, boolean | undefined> | undefined): string[] {".to_owned());
    out.push("  if (!select) return [];".to_owned());
    out.push("  return Object.entries(select)".to_owned());
    out.push("    .filter(([, enabled]) => enabled)".to_owned());
    out.push("    .map(([key]) => key);".to_owned());
    out.push("}".to_owned());
    out.push(String::new());
}

fn emit_surreal_like(out: &mut Vec<String>) {
    out.push("export type SurrealLike = {".to_owned());
    out.push(
        "  query<T = unknown>(sql: string, vars?: Record<string, unknown>): Promise<T>;"
            .to_owned(),
    );
    out.push("  select<T = unknown>(thing: string): Promise<T>;".to_owned());
    out.push(
        "  create<T = unknown>(thing: string, data?: Record<string, unknown>): Promise<T>;"
            .to_owned(),
    );
    out.push(
        "  merge<T = unknown>(thing: string, data?: Record<string, unknown>): Promise<T>;"
            .to_owned(),
    );
    out.push("  delete<T = unknown>(thing: string): Promise<T>;".to_owned());
    out.push("};".to_owned());
    out.push(String::new());
}

fn emit_shared_runtime(out: &mut Vec<String>) {
    out.push("async function selectRecord<T>(".to_owned());
    out.push("  db: SurrealLike,".to_owned());
    out.push("  table: string,".to_owned());
    out.push("  id: string,".to_owned());
    out.push("): Promise<T | undefined> {".to_owned());
    out.push("  const thing = normalizeThing(table, id);".to_owned());
    out.push("  return firstRow<T>(await db.select(thing));".to_owned());
    out.push("}".to_owned());
    out.push(String::new());

    out.push("async function selectRecordRelated<T>(".to_owned());
    out.push("  db: SurrealLike,".to_owned());
    out.push("  table: string,".to_owned());
    out.push("  id: string,".to_owned());
    out.push("  fetch: string[],".to_owned());
    out.push("): Promise<T | undefined> {".to_owned());
    out.push("  const thing = normalizeThing(table, id);".to_owned());
    out.push("  if (fetch.length === 0) return firstRow<T>(await db.select(thing));".to_owned());
    out.push(
        "  const row = await db.query(`SELECT * FROM type::record($thing) FETCH ${fetch.join(\", \")}`, { thing });"
            .to_owned(),
    );
    out.push("  return firstRow<T>(row);".to_owned());
    out.push("}".to_owned());
    out.push(String::new());

    out.push("async function createRecord<T>(".to_owned());
    out.push("  db: SurrealLike,".to_owned());
    out.push("  table: string,".to_owned());
    out.push("  data: Record<string, unknown>,".to_owned());
    out.push("): Promise<T> {".to_owned());
    out.push("  const created = await firstRow<T>(await db.create(table, data));".to_owned());
    out.push("  if (!created) throw new Error(`create ${table} returned no row`);".to_owned());
    out.push("  return created;".to_owned());
    out.push("}".to_owned());
    out.push(String::new());

    out.push("async function updateRecord<T>(".to_owned());
    out.push("  db: SurrealLike,".to_owned());
    out.push("  table: string,".to_owned());
    out.push("  id: string,".to_owned());
    out.push("  data: Record<string, unknown>,".to_owned());
    out.push("): Promise<T | undefined> {".to_owned());
    out.push("  const thing = normalizeThing(table, id);".to_owned());
    out.push("  return firstRow<T>(await db.merge(thing, data));".to_owned());
    out.push("}".to_owned());
    out.push(String::new());

    out.push("async function deleteRecord(".to_owned());
    out.push("  db: SurrealLike,".to_owned());
    out.push("  table: string,".to_owned());
    out.push("  id: string,".to_owned());
    out.push("): Promise<void> {".to_owned());
    out.push("  await db.delete(normalizeThing(table, id));".to_owned());
    out.push("}".to_owned());
    out.push(String::new());

    out.push("async function queryRows<T>(".to_owned());
    out.push("  db: SurrealLike,".to_owned());
    out.push("  sql: string,".to_owned());
    out.push("  vars?: Record<string, unknown>,".to_owned());
    out.push("): Promise<T[]> {".to_owned());
    out.push("  return asRows<T>(await db.query(sql, vars));".to_owned());
    out.push("}".to_owned());
    out.push(String::new());

    out.push("function projectField(".to_owned());
    out.push("  key: string,".to_owned());
    out.push("  value: unknown,".to_owned());
    out.push("  fieldMeta: FieldSelectMeta,".to_owned());
    out.push("  allMeta: Record<string, Record<string, FieldSelectMeta>>,".to_owned());
    out.push("): string | null {".to_owned());
    out.push("  if (value === false || value == null) return null;".to_owned());
    out.push("  if (fieldMeta.kind === \"scalar\") return key;".to_owned());
    out.push("  if (value === true) {".to_owned());
    out.push("    if (fieldMeta.kind === \"edge\") {".to_owned());
    out.push(
        "      const arrow = fieldMeta.dir === \"out\" ? `->${fieldMeta.edgeTable}` : `<-${fieldMeta.edgeTable}`;"
            .to_owned(),
    );
    out.push("      return `${arrow}.* AS ${key}`;".to_owned());
    out.push("    }".to_owned());
    out.push("    return `${key}.*`;".to_owned());
    out.push("  }".to_owned());
    out.push("  if (typeof value === \"object\" && value !== null && \"select\" in value) {".to_owned());
    out.push(
        "    const nestedSelect = (value as { select?: Record<string, unknown> }).select;"
            .to_owned(),
    );
    out.push("    const nestedTable =".to_owned());
    out.push(
        "      fieldMeta.kind === \"edge\" ? fieldMeta.edgeTable : fieldMeta.targetTable;"
            .to_owned(),
    );
    out.push(
        "    const nested = buildProjection(nestedSelect, nestedTable, allMeta);"
            .to_owned(),
    );
    out.push("    if (fieldMeta.kind === \"edge\") {".to_owned());
    out.push(
        "      const arrow = fieldMeta.dir === \"out\" ? `->${fieldMeta.edgeTable}` : `<-${fieldMeta.edgeTable}`;"
            .to_owned(),
    );
    out.push("      return `${arrow}.{ ${nested} } AS ${key}`;".to_owned());
    out.push("    }".to_owned());
    out.push("    return `${key}.{ ${nested} }`;".to_owned());
    out.push("  }".to_owned());
    out.push("  return null;".to_owned());
    out.push("}".to_owned());
    out.push(String::new());

    out.push("function buildProjection(".to_owned());
    out.push("  select: Record<string, unknown> | undefined,".to_owned());
    out.push("  table: string,".to_owned());
    out.push(
        "  allMeta: Record<string, Record<string, FieldSelectMeta>> = SelectMetaByTable,"
            .to_owned(),
    );
    out.push("): string {".to_owned());
    out.push("  if (!select) return \"*\";".to_owned());
    out.push("  const meta = allMeta[table] ?? {};".to_owned());
    out.push("  const parts: string[] = [];".to_owned());
    out.push("  for (const [key, value] of Object.entries(select)) {".to_owned());
    out.push("    const fieldMeta = meta[key];".to_owned());
    out.push("    if (!fieldMeta) continue;".to_owned());
    out.push("    const part = projectField(key, value, fieldMeta, allMeta);".to_owned());
    out.push("    if (part) parts.push(part);".to_owned());
    out.push("  }".to_owned());
    out.push("  return parts.length === 0 ? \"*\" : parts.join(\", \");".to_owned());
    out.push("}".to_owned());
    out.push(String::new());

    out.push("async function findUniqueRecord<T>(".to_owned());
    out.push("  db: SurrealLike,".to_owned());
    out.push("  table: string,".to_owned());
    out.push("  id: string,".to_owned());
    out.push("  select?: Record<string, unknown>,".to_owned());
    out.push("): Promise<T | undefined> {".to_owned());
    out.push("  if (!select) return selectRecord<T>(db, table, id);".to_owned());
    out.push("  const thing = normalizeThing(table, id);".to_owned());
    out.push("  const projection = buildProjection(select, table);".to_owned());
    out.push(
        "  const row = await db.query(`SELECT ${projection} FROM type::record($thing)`, { thing });"
            .to_owned(),
    );
    out.push("  return firstRow<T>(row);".to_owned());
    out.push("}".to_owned());
    out.push(String::new());

    out.push("async function findManyRecords<T>(".to_owned());
    out.push("  db: SurrealLike,".to_owned());
    out.push("  table: string,".to_owned());
    out.push("  args: {".to_owned());
    out.push("    select?: Record<string, unknown>;".to_owned());
    out.push("    whereSql?: string;".to_owned());
    out.push("    vars?: Record<string, unknown>;".to_owned());
    out.push("  } = {},".to_owned());
    out.push("): Promise<T[]> {".to_owned());
    out.push("  if (!args.select) {".to_owned());
    out.push(
        "    const sql = args.whereSql ?? `SELECT * FROM ${table}`;"
            .to_owned(),
    );
    out.push("    return queryRows<T>(db, sql, args.vars);".to_owned());
    out.push("  }".to_owned());
    out.push("  const projection = buildProjection(args.select, table);".to_owned());
    out.push("  if (args.whereSql) {".to_owned());
    out.push(
        "    const sql = args.whereSql.replace(/^\\s*SELECT\\s+\\*/i, `SELECT ${projection}`);"
            .to_owned(),
    );
    out.push("    return queryRows<T>(db, sql, args.vars);".to_owned());
    out.push("  }".to_owned());
    out.push(
        "  return queryRows<T>(db, `SELECT ${projection} FROM ${table}`, args.vars);"
            .to_owned(),
    );
    out.push("}".to_owned());
    out.push(String::new());
}

fn emit_select_helpers(out: &mut Vec<String>, schema: &DatabaseSchema, naming: &NamingContext<'_>) {
    for model in &schema.models {
        let table = model.table_name(naming.convention());
        let fetch_fields = fetch_field_names(model, naming);
        let fetch_lit = js_string_array(&fetch_fields);
        out.push(format!(
            "/** Fetch stored `{name}` row (links as RecordId). */",
            name = model.name
        ));
        out.push(format!(
            "export async function select{}(db: SurrealLike, id: RecordId<\"{table}\"> | string): Promise<{} | undefined> {{",
            model.name, model.name
        ));
        out.push(format!(
            "  return selectRecord<{}>(db, \"{table}\", id);",
            model.name
        ));
        out.push("}".to_owned());
        out.push(String::new());

        out.push(format!(
            "/** Fetch `{name}` with related link/@relation fields expanded. */",
            name = model.name
        ));
        out.push(format!(
            "export async function select{}Related(db: SurrealLike, id: RecordId<\"{table}\"> | string): Promise<{}Selected | undefined> {{",
            model.name, model.name
        ));
        out.push(format!(
            "  return selectRecordRelated<{}Selected>(db, \"{table}\", id, {fetch_lit});",
            model.name
        ));
        out.push("}".to_owned());
        out.push(String::new());
    }

    for edge in &schema.edges {
        let table = edge.table_name(naming.convention());
        out.push(format!("/** Fetch stored `{name}` edge row. */", name = edge.name));
        out.push(format!(
            "export async function select{}(db: SurrealLike, id: RecordId<\"{table}\"> | string): Promise<{} | undefined> {{",
            edge.name, edge.name
        ));
        out.push(format!(
            "  return selectRecord<{}>(db, \"{table}\", id);",
            edge.name
        ));
        out.push("}".to_owned());
        out.push(String::new());

        out.push(format!(
            "/** Fetch `{name}` edge with `in`/`out` expanded. */",
            name = edge.name
        ));
        out.push(format!(
            "export async function select{}Related(db: SurrealLike, id: RecordId<\"{table}\"> | string): Promise<{}Selected | undefined> {{",
            edge.name, edge.name
        ));
        out.push(format!(
            "  return selectRecordRelated<{}Selected>(db, \"{table}\", id, [\"in\", \"out\"]);",
            edge.name
        ));
        out.push("}".to_owned());
        out.push(String::new());
    }
}

fn emit_crud_helpers(out: &mut Vec<String>, schema: &DatabaseSchema, naming: &NamingContext<'_>) {
    for model in &schema.models {
        let table = model.table_name(naming.convention());
        out.push(format!(
            "export async function create{}(db: SurrealLike, data: {}CreateInput): Promise<{}> {{",
            model.name, model.name, model.name
        ));
        out.push(format!(
            "  return createRecord<{}>(db, \"{table}\", data as Record<string, unknown>);",
            model.name
        ));
        out.push("}".to_owned());
        out.push(String::new());

        out.push(format!(
            "export async function update{}(db: SurrealLike, id: RecordId<\"{table}\"> | string, data: {}UpdateInput): Promise<{} | undefined> {{",
            model.name, model.name, model.name
        ));
        out.push(format!(
            "  return updateRecord<{}>(db, \"{table}\", id, data as Record<string, unknown>);",
            model.name
        ));
        out.push("}".to_owned());
        out.push(String::new());

        out.push(format!(
            "export async function delete{}(db: SurrealLike, id: RecordId<\"{table}\"> | string): Promise<void> {{",
            model.name
        ));
        out.push(format!("  return deleteRecord(db, \"{table}\", id);"));
        out.push("}".to_owned());
        out.push(String::new());
    }

    for edge in &schema.edges {
        let table = edge.table_name(naming.convention());
        let in_table = table_for_model_name(schema, &edge.in_model, naming);
        let out_table = table_for_model_name(schema, &edge.out_model, naming);
        out.push(format!(
            "export async function create{}(db: SurrealLike, data: {}CreateInput): Promise<{}> {{",
            edge.name, edge.name, edge.name
        ));
        out.push(format!(
            "  const row = await db.query(`RELATE $in->{table}->$out CONTENT $content`, {{"
        ));
        out.push(format!("    in: normalizeThing(\"{in_table}\", String(data.in)),"));
        out.push(format!("    out: normalizeThing(\"{out_table}\", String(data.out)),"));
        out.push("    content: Object.fromEntries(".to_owned());
        out.push(
            "      Object.entries(data).filter(([key]) => key !== \"in\" && key !== \"out\"),"
                .to_owned(),
        );
        out.push("    ),".to_owned());
        out.push("  });".to_owned());
        out.push(format!(
            "  const created = await firstRow<{}>(row);",
            edge.name
        ));
        out.push(format!(
            "  if (!created) throw new Error(\"create{} returned no row\");",
            edge.name
        ));
        out.push("  return created;".to_owned());
        out.push("}".to_owned());
        out.push(String::new());

        out.push(format!(
            "export async function update{}(db: SurrealLike, id: RecordId<\"{table}\"> | string, data: {}UpdateInput): Promise<{} | undefined> {{",
            edge.name, edge.name, edge.name
        ));
        out.push(format!(
            "  return updateRecord<{}>(db, \"{table}\", id, data as Record<string, unknown>);",
            edge.name
        ));
        out.push("}".to_owned());
        out.push(String::new());

        out.push(format!(
            "export async function delete{}(db: SurrealLike, id: RecordId<\"{table}\"> | string): Promise<void> {{",
            edge.name
        ));
        out.push(format!("  return deleteRecord(db, \"{table}\", id);"));
        out.push("}".to_owned());
        out.push(String::new());
    }
}

fn emit_query_helpers(out: &mut Vec<String>, schema: &DatabaseSchema, _naming: &NamingContext<'_>) {
    for model in &schema.models {
        let fn_name = query_fn_name(&model.name);
        let related = query_related_fn_name(&model.name);
        out.push(format!(
            "export async function {fn_name}(db: SurrealLike, sql: string, vars?: Record<string, unknown>): Promise<{}[]> {{",
            model.name
        ));
        out.push(format!("  return queryRows<{}>(db, sql, vars);", model.name));
        out.push("}".to_owned());
        out.push(String::new());

        out.push(format!(
            "export async function {related}(db: SurrealLike, sql: string, vars?: Record<string, unknown>): Promise<{}Selected[]> {{",
            model.name
        ));
        out.push(format!(
            "  return queryRows<{}Selected>(db, sql, vars);",
            model.name
        ));
        out.push("}".to_owned());
        out.push(String::new());
    }

    for edge in &schema.edges {
        let fn_name = query_fn_name(&edge.name);
        let related = query_related_fn_name(&edge.name);
        out.push(format!(
            "export async function {fn_name}(db: SurrealLike, sql: string, vars?: Record<string, unknown>): Promise<{}[]> {{",
            edge.name
        ));
        out.push(format!("  return queryRows<{}>(db, sql, vars);", edge.name));
        out.push("}".to_owned());
        out.push(String::new());

        out.push(format!(
            "export async function {related}(db: SurrealLike, sql: string, vars?: Record<string, unknown>): Promise<{}Selected[]> {{",
            edge.name
        ));
        out.push(format!(
            "  return queryRows<{}Selected>(db, sql, vars);",
            edge.name
        ));
        out.push("}".to_owned());
        out.push(String::new());
    }
}

fn emit_fluent_client(out: &mut Vec<String>, schema: &DatabaseSchema, naming: &NamingContext<'_>) {
    out.push("export function createClient(db: SurrealLike) {".to_owned());
    out.push("  return {".to_owned());

    for model in &schema.models {
        let key = client_key(&model.name);
        let table = model.table_name(naming.convention());
        out.push(format!("    {key}: {{"));
        out.push(format!(
            "      findUnique: <S extends {}Select | undefined = undefined>(args: {{",
            model.name
        ));
        out.push(format!("        where: {{ id: RecordId<\"{table}\"> | string }};"));
        out.push("        select?: S;".to_owned());
        out.push(format!(
            "      }}): Promise<{}GetPayload<S> | undefined> =>",
            model.name
        ));
        out.push(format!(
            "        findUniqueRecord(db, \"{table}\", args.where.id, args.select as Record<string, unknown> | undefined) as Promise<{}GetPayload<S> | undefined>,",
            model.name
        ));
        out.push(format!(
            "      findMany: <S extends {}Select | undefined = undefined>(args: {{",
            model.name
        ));
        out.push("        select?: S;".to_owned());
        out.push("        whereSql?: string;".to_owned());
        out.push("        vars?: Record<string, unknown>;".to_owned());
        out.push(format!(
            "      }} = {{}}): Promise<{}GetPayload<S>[]> =>",
            model.name
        ));
        out.push(format!(
            "        findManyRecords(db, \"{table}\", args as {{ select?: Record<string, unknown>; whereSql?: string; vars?: Record<string, unknown> }}) as Promise<{}GetPayload<S>[]>,",
            model.name
        ));
        out.push(format!(
            "      create: (data: {}CreateInput): Promise<{}> => create{}(db, data),",
            model.name, model.name, model.name
        ));
        out.push(format!(
            "      update: (id: RecordId<\"{table}\"> | string, data: {}UpdateInput): Promise<{} | undefined> => update{}(db, id, data),",
            model.name, model.name, model.name
        ));
        out.push(format!(
            "      delete: (id: RecordId<\"{table}\"> | string): Promise<void> => delete{}(db, id),",
            model.name
        ));
        out.push("    },".to_owned());
    }

    for edge in &schema.edges {
        let key = client_key(&edge.name);
        let table = edge.table_name(naming.convention());
        out.push(format!("    {key}: {{"));
        out.push(format!(
            "      findUnique: <S extends {}Select | undefined = undefined>(args: {{",
            edge.name
        ));
        out.push(format!("        where: {{ id: RecordId<\"{table}\"> | string }};"));
        out.push("        select?: S;".to_owned());
        out.push(format!(
            "      }}): Promise<{}GetPayload<S> | undefined> =>",
            edge.name
        ));
        out.push(format!(
            "        findUniqueRecord(db, \"{table}\", args.where.id, args.select as Record<string, unknown> | undefined) as Promise<{}GetPayload<S> | undefined>,",
            edge.name
        ));
        out.push(format!(
            "      create: (data: {}CreateInput): Promise<{}> => create{}(db, data),",
            edge.name, edge.name, edge.name
        ));
        out.push(format!(
            "      update: (id: RecordId<\"{table}\"> | string, data: {}UpdateInput): Promise<{} | undefined> => update{}(db, id, data),",
            edge.name, edge.name, edge.name
        ));
        out.push(format!(
            "      delete: (id: RecordId<\"{table}\"> | string): Promise<void> => delete{}(db, id),",
            edge.name
        ));
        out.push("    },".to_owned());
    }

    out.push("  } as const;".to_owned());
    out.push("}".to_owned());
    out.push(String::new());
}

fn js_string_array(items: &[String]) -> String {
    if items.is_empty() {
        "[]".to_owned()
    } else {
        format!(
            "[{}]",
            items
                .iter()
                .map(|item| format!("\"{item}\""))
                .collect::<Vec<_>>()
                .join(", ")
        )
    }
}

fn fetch_field_names(model: &Model, naming: &NamingContext<'_>) -> Vec<String> {
    model
        .fields
        .iter()
        .filter(|field| !field.name.contains('.'))
        .filter(|field| field.is_link() || field.relation_name.is_some())
        .map(|field| naming.field_name(field))
        .collect()
}
