#![allow(clippy::missing_errors_doc, clippy::too_many_lines)]

use codegen::CodeGenerator;
use core::usecases::CodeGeneratorPort;
use core::{
    DatabaseSchema, DomainError, Edge, Field, FieldType, Model, NamingContext, ObjectTypeDefinition,
};

pub struct TypeScriptGenerator;

impl TypeScriptGenerator {
    #[must_use]
    pub const fn new() -> Self {
        Self
    }
}

impl Default for TypeScriptGenerator {
    fn default() -> Self {
        Self::new()
    }
}

impl CodeGenerator for TypeScriptGenerator {
    fn language(&self) -> &'static str {
        "typescript"
    }

    fn generate(&self, schema: &DatabaseSchema) -> Result<String, DomainError> {
        Ok(emit_typescript(schema))
    }
}

impl CodeGeneratorPort for TypeScriptGenerator {
    fn generate(&self, schema: &DatabaseSchema) -> Result<String, DomainError> {
        CodeGenerator::generate(self, schema)
    }
}

fn emit_typescript(schema: &DatabaseSchema) -> String {
    let naming = NamingContext::new(&schema.naming, &schema.models);
    let mut out = vec![
        "// Generated by Awesome Schema".to_owned(),
        "// Requires a SurrealDB JS client compatible with SurrealLike (e.g. `surrealdb`).".to_owned(),
        "// Prefer `recordId(Tables.User, key)` for branded ids.".to_owned(),
        String::new(),
        "/** Surreal record id branded by table name. */".to_owned(),
        "export type RecordId<Table extends string = string> =".to_owned(),
        "  string & { readonly __table?: Table };".to_owned(),
        String::new(),
    ];

    for object_type in &schema.object_types {
        emit_object_type(&mut out, object_type, &naming);
    }

    for model in &schema.models {
        emit_model_record(&mut out, schema, model, &naming);
        emit_model_selected(&mut out, schema, model, &naming);
        emit_model_inputs(&mut out, schema, model, &naming);
    }

    for edge in &schema.edges {
        emit_edge_record(&mut out, schema, edge, &naming);
        emit_edge_selected(&mut out, schema, edge, &naming);
        emit_edge_inputs(&mut out, schema, edge, &naming);
    }

    emit_select_type_utils(&mut out);
    for model in &schema.models {
        emit_model_select_payload(&mut out, schema, model, &naming);
    }
    for edge in &schema.edges {
        emit_edge_select_payload(&mut out, schema, edge, &naming);
    }

    emit_where_shared_types(&mut out);
    for model in &schema.models {
        emit_model_where_input(&mut out, schema, model, &naming);
        emit_model_where_unique_input(&mut out, model, &naming);
    }
    for edge in &schema.edges {
        emit_edge_where_input(&mut out, schema, edge, &naming);
        emit_edge_where_unique_input(&mut out, edge, &naming);
    }

    emit_order_by_shared_types(&mut out);
    for model in &schema.models {
        emit_model_order_by_input(&mut out, model, &naming);
    }
    for edge in &schema.edges {
        emit_edge_order_by_input(&mut out, edge, &naming);
    }

    emit_tables_const(&mut out, schema, &naming);
    emit_select_meta_registry(&mut out, schema, &naming);
    emit_record_id_helpers(&mut out);
    emit_surreal_like(&mut out);
    emit_shared_runtime(&mut out);
    emit_select_helpers(&mut out, schema, &naming);
    emit_crud_helpers(&mut out, schema, &naming);
    emit_query_helpers(&mut out, schema, &naming);
    emit_fluent_client(&mut out, schema, &naming);

    out.join("\n")
}

fn emit_object_type(out: &mut Vec<String>, object_type: &ObjectTypeDefinition, naming: &NamingContext<'_>) {
    out.push(format!("export type {} = {{", object_type.name));
    for field in &object_type.fields {
        let ts = map_object_field_type(&field.field_type, naming);
        let optional = if field.optional { "?" } else { "" };
        out.push(format!("  {}{optional}: {};", field.name, ts));
    }
    if object_type.flexible {
        out.push("  [key: string]: unknown;".to_owned());
    }
    out.push("};".to_owned());
    out.push(String::new());
}

fn emit_model_record(
    out: &mut Vec<String>,
    schema: &DatabaseSchema,
    model: &Model,
    naming: &NamingContext<'_>,
) {
    out.push(format!("export type {} = {{", model.name));
    for field in model.fields.iter().filter(|f| !f.name.contains('.')) {
        if should_omit_on_record(field) {
            continue;
        }
        let ts = map_model_field_record(schema, model, field, naming);
        let optional = if field.optional { "?" } else { "" };
        let name = naming.field_name(field);
        out.push(format!("  {name}{optional}: {ts};"));
    }
    out.push("};".to_owned());
    out.push(String::new());
}

fn emit_model_selected(
    out: &mut Vec<String>,
    schema: &DatabaseSchema,
    model: &Model,
    naming: &NamingContext<'_>,
) {
    out.push(format!("export type {}Selected = {{", model.name));
    for field in model.fields.iter().filter(|f| !f.name.contains('.')) {
        let ts = map_model_field_selected(schema, model, field, naming);
        let optional = if field.optional || field.is_computed_link() || field.relation_name.is_some()
        {
            "?"
        } else {
            ""
        };
        let name = naming.field_name(field);
        out.push(format!("  {name}{optional}: {ts};"));
    }
    out.push("};".to_owned());
    out.push(String::new());
}

fn emit_model_inputs(
    out: &mut Vec<String>,
    schema: &DatabaseSchema,
    model: &Model,
    naming: &NamingContext<'_>,
) {
    out.push(format!("export type {}CreateInput = {{", model.name));
    for field in model.fields.iter().filter(|f| !f.name.contains('.')) {
        if field.is_id || should_omit_on_record(field) {
            continue;
        }
        let ts = map_model_field_record(schema, model, field, naming);
        let optional = if field.optional { "?" } else { "" };
        let name = naming.field_name(field);
        out.push(format!("  {name}{optional}: {ts};"));
    }
    out.push("};".to_owned());
    out.push(String::new());

    out.push(format!("export type {}UpdateInput = {{", model.name));
    for field in model.fields.iter().filter(|f| !f.name.contains('.')) {
        if field.is_id || should_omit_on_record(field) {
            continue;
        }
        let ts = map_model_field_record(schema, model, field, naming);
        let name = naming.field_name(field);
        out.push(format!("  {name}?: {ts};"));
    }
    out.push("};".to_owned());
    out.push(String::new());
}

fn emit_select_type_utils(out: &mut Vec<String>) {
    out.push("/** `true` or nested `{ select }` for a related entity. */".to_owned());
    out.push("export type SelectArg<S> = boolean | { select?: S };".to_owned());
    out.push(String::new());
    out.push(
        "/** Resolve one select entry: `true` → Default; `{ select: N }` → nested payload. */"
            .to_owned(),
    );
    out.push("export type ResolveSelectField<".to_owned());
    out.push("  V,".to_owned());
    out.push("  Default,".to_owned());
    out.push("  NestedSelect,".to_owned());
    out.push("  NestedPayload,".to_owned());
    out.push("> = V extends true".to_owned());
    out.push("  ? Default".to_owned());
    out.push("  : V extends { select?: NestedSelect }".to_owned());
    out.push("    ? NestedPayload".to_owned());
    out.push("    : never;".to_owned());
    out.push(String::new());
}

fn emit_where_shared_types(out: &mut Vec<String>) {
    out.push("export type StringFilter = {".to_owned());
    out.push("  equals?: string;".to_owned());
    out.push("  in?: string[];".to_owned());
    out.push("  contains?: string;".to_owned());
    out.push("  gt?: string;".to_owned());
    out.push("  gte?: string;".to_owned());
    out.push("  lt?: string;".to_owned());
    out.push("  lte?: string;".to_owned());
    out.push("};".to_owned());
    out.push(String::new());
    out.push("export type NumberFilter = {".to_owned());
    out.push("  equals?: number;".to_owned());
    out.push("  in?: number[];".to_owned());
    out.push("  gt?: number;".to_owned());
    out.push("  gte?: number;".to_owned());
    out.push("  lt?: number;".to_owned());
    out.push("  lte?: number;".to_owned());
    out.push("};".to_owned());
    out.push(String::new());
    out.push("export type BooleanFilter = { equals?: boolean };".to_owned());
    out.push(String::new());
    out.push("export type DateFilter = {".to_owned());
    out.push("  equals?: Date | string;".to_owned());
    out.push("  in?: Array<Date | string>;".to_owned());
    out.push("  gt?: Date | string;".to_owned());
    out.push("  gte?: Date | string;".to_owned());
    out.push("  lt?: Date | string;".to_owned());
    out.push("  lte?: Date | string;".to_owned());
    out.push("};".to_owned());
    out.push(String::new());
    out.push("export type JsonFilter = { equals?: unknown };".to_owned());
    out.push(String::new());
    out.push("export type ArrayFilter = {".to_owned());
    out.push("  equals?: unknown[];".to_owned());
    out.push("  contains?: unknown;".to_owned());
    out.push("};".to_owned());
    out.push(String::new());
    out.push("export type IdFilter = { equals?: string; in?: string[] };".to_owned());
    out.push(String::new());
    out.push("export type ListRelationFilter<W> = {".to_owned());
    out.push("  some?: W;".to_owned());
    out.push("  every?: W;".to_owned());
    out.push("  none?: W;".to_owned());
    out.push("};".to_owned());
    out.push(String::new());
    out.push("export type RelationFilter<W> = {".to_owned());
    out.push("  is?: W;".to_owned());
    out.push("};".to_owned());
    out.push(String::new());
}

fn emit_model_where_input(
    out: &mut Vec<String>,
    schema: &DatabaseSchema,
    model: &Model,
    naming: &NamingContext<'_>,
) {
    out.push(format!("export type {}WhereInput = {{", model.name));
    out.push(format!("  AND?: {}WhereInput | {}WhereInput[];", model.name, model.name));
    out.push(format!("  OR?: {}WhereInput[];", model.name));
    out.push(format!("  NOT?: {}WhereInput | {}WhereInput[];", model.name, model.name));
    for field in model.fields.iter().filter(|f| !f.name.contains('.')) {
        let name = naming.field_name(field);
        if let Some(relation) = &field.relation_name {
            let edge = resolve_edge_type_name(schema, relation);
            out.push(format!(
                "  {name}?: {edge}WhereInput | ListRelationFilter<{edge}WhereInput>;"
            ));
        } else if field.is_link() {
            let target = field
                .link_target
                .as_deref()
                .or_else(|| field.field_type.link_model_name())
                .unwrap_or("unknown");
            if field.is_list_link() {
                out.push(format!(
                    "  {name}?: {target}WhereInput | ListRelationFilter<{target}WhereInput>;"
                ));
            } else {
                out.push(format!(
                    "  {name}?: {target}WhereInput | RelationFilter<{target}WhereInput>;"
                ));
            }
        } else if !should_omit_on_record(field) {
            let filter_ts = where_scalar_union(&field.field_type, field.is_id);
            out.push(format!("  {name}?: {filter_ts};"));
        }
    }
    out.push("};".to_owned());
    out.push(String::new());
}

fn emit_edge_where_input(
    out: &mut Vec<String>,
    _schema: &DatabaseSchema,
    edge: &Edge,
    naming: &NamingContext<'_>,
) {
    out.push(format!("export type {}WhereInput = {{", edge.name));
    out.push(format!("  AND?: {}WhereInput | {}WhereInput[];", edge.name, edge.name));
    out.push(format!("  OR?: {}WhereInput[];", edge.name));
    out.push(format!("  NOT?: {}WhereInput | {}WhereInput[];", edge.name, edge.name));
    out.push("  id?: string | IdFilter;".to_owned());
    out.push(format!(
        "  in?: {}WhereInput | RelationFilter<{}WhereInput>;",
        edge.in_model, edge.in_model
    ));
    out.push(format!(
        "  out?: {}WhereInput | RelationFilter<{}WhereInput>;",
        edge.out_model, edge.out_model
    ));
    for field in edge.fields.iter().filter(|f| !f.name.contains('.')) {
        let name = naming.field_name(field);
        let filter_ts = where_scalar_union(&field.field_type, false);
        out.push(format!("  {name}?: {filter_ts};"));
    }
    out.push("};".to_owned());
    out.push(String::new());
}

fn emit_model_where_unique_input(out: &mut Vec<String>, model: &Model, naming: &NamingContext<'_>) {
    out.push(format!("export type {}WhereUniqueInput = {{", model.name));
    for field in model.fields.iter().filter(|f| !f.name.contains('.')) {
        if field.is_link() || field.relation_name.is_some() {
            continue;
        }
        if field.is_id {
            let name = naming.field_name(field);
            out.push(format!("  {name}?: string | IdFilter;"));
        } else if field.unique {
            let name = naming.field_name(field);
            let filter_ts = where_scalar_union(&field.field_type, false);
            out.push(format!("  {name}?: {filter_ts};"));
        }
    }
    out.push("};".to_owned());
    out.push(String::new());
}

fn emit_edge_where_unique_input(out: &mut Vec<String>, edge: &Edge, naming: &NamingContext<'_>) {
    out.push(format!("export type {}WhereUniqueInput = {{", edge.name));
    out.push("  id?: string | IdFilter;".to_owned());
    for field in edge.fields.iter().filter(|f| !f.name.contains('.') && f.unique) {
        let name = naming.field_name(field);
        let filter_ts = where_scalar_union(&field.field_type, false);
        out.push(format!("  {name}?: {filter_ts};"));
    }
    out.push("};".to_owned());
    out.push(String::new());
}

const fn scalar_filter_kind(field_type: &FieldType, is_id: bool) -> &'static str {
    if is_id {
        return "id";
    }
    match field_type {
        FieldType::String => "string",
        FieldType::Int | FieldType::Float => "number",
        FieldType::Bool => "boolean",
        FieldType::Datetime => "datetime",
        FieldType::Array(_) => "array",
        FieldType::RecordId(_) => "id",
        FieldType::Object | FieldType::Model(_) | FieldType::Custom(_) => "json",
    }
}

fn where_scalar_union(field_type: &FieldType, is_id: bool) -> String {
    match scalar_filter_kind(field_type, is_id) {
        "string" => "string | StringFilter".to_owned(),
        "number" => "number | NumberFilter".to_owned(),
        "boolean" => "boolean | BooleanFilter".to_owned(),
        "datetime" => "Date | string | DateFilter".to_owned(),
        "array" => "unknown[] | ArrayFilter".to_owned(),
        "id" => "string | IdFilter".to_owned(),
        _ => "unknown | JsonFilter".to_owned(),
    }
}

fn emit_order_by_shared_types(out: &mut Vec<String>) {
    out.push("export type SortOrder = \"asc\" | \"desc\";".to_owned());
    out.push(String::new());
}

fn emit_model_order_by_input(out: &mut Vec<String>, model: &Model, naming: &NamingContext<'_>) {
    out.push(format!("export type {}OrderByInput = {{", model.name));
    for field in model.fields.iter().filter(|f| !f.name.contains('.')) {
        if field.is_link() || field.relation_name.is_some() || should_omit_on_record(field) {
            continue;
        }
        let name = naming.field_name(field);
        out.push(format!("  {name}?: SortOrder;"));
    }
    out.push("};".to_owned());
    out.push(String::new());
}

fn emit_edge_order_by_input(out: &mut Vec<String>, edge: &Edge, naming: &NamingContext<'_>) {
    out.push(format!("export type {}OrderByInput = {{", edge.name));
    out.push("  id?: SortOrder;".to_owned());
    for field in edge.fields.iter().filter(|f| !f.name.contains('.')) {
        let name = naming.field_name(field);
        out.push(format!("  {name}?: SortOrder;"));
    }
    out.push("};".to_owned());
    out.push(String::new());
}

fn emit_model_select_payload(
    out: &mut Vec<String>,
    schema: &DatabaseSchema,
    model: &Model,
    naming: &NamingContext<'_>,
) {
    let fields: Vec<&Field> = model
        .fields
        .iter()
        .filter(|field| !field.name.contains('.'))
        .filter(|field| {
            !should_omit_on_record(field) || field.is_link() || field.relation_name.is_some()
        })
        .collect();

    out.push(format!("export type {}Scalars = {{", model.name));
    for field in &fields {
        if field.is_link() || field.relation_name.is_some() {
            continue;
        }
        let name = naming.field_name(field);
        let ts = map_model_field_record(schema, model, field, naming);
        out.push(format!("  {name}: {ts};"));
    }
    out.push("};".to_owned());
    out.push(String::new());

    out.push(format!("export type {}Select = {{", model.name));
    for field in &fields {
        let name = naming.field_name(field);
        if field.is_link() || field.relation_name.is_some() {
            let target_select = relation_select_type_name(schema, field);
            out.push(format!("  {name}?: SelectArg<{target_select}>;"));
        } else {
            out.push(format!("  {name}?: boolean;"));
        }
    }
    out.push("};".to_owned());
    out.push(String::new());

    for field in fields.iter().filter(|f| f.is_link() || f.relation_name.is_some()) {
        let name = naming.field_name(field);
        let alias = format!("{}{}Field", model.name, pascal_case(&name));
        let (default_ty, nested_select, list) = relation_payload_parts(schema, field);
        let default = if list {
            format!("{default_ty}[]")
        } else {
            default_ty.clone()
        };
        let nested_payload = if list {
            format!("{default_ty}GetPayload<N>[]")
        } else {
            format!("{default_ty}GetPayload<N>")
        };
        out.push(format!("type {alias}<V> = V extends true"));
        out.push(format!("  ? {default}"));
        out.push(format!(
            "  : V extends {{ select?: infer N extends {nested_select} | undefined }}"
        ));
        out.push(format!("    ? {nested_payload}"));
        out.push("    : never;".to_owned());
        out.push(String::new());
    }

    out.push(format!(
        "export type {}GetPayload<S extends {}Select | undefined = undefined> =",
        model.name, model.name
    ));
    out.push("  [S] extends [undefined]".to_owned());
    out.push(format!("    ? {}", model.name));
    out.push("    : {".to_owned());
    out.push(
        "        [K in keyof S as S[K] extends false | undefined ? never : K]-?:"
            .to_owned(),
    );
    out.push(format!("          K extends keyof {}Scalars", model.name));
    out.push(format!("            ? {}Scalars[K]", model.name));
    for field in fields.iter().filter(|f| f.is_link() || f.relation_name.is_some()) {
        let name = naming.field_name(field);
        let alias = format!("{}{}Field", model.name, pascal_case(&name));
        out.push(format!("            : K extends \"{name}\""));
        out.push(format!("              ? {alias}<S[K]>"));
    }
    out.push("            : never;".to_owned());
    out.push("      };".to_owned());
    out.push(String::new());
}

fn emit_edge_record(
    out: &mut Vec<String>,
    schema: &DatabaseSchema,
    edge: &Edge,
    naming: &NamingContext<'_>,
) {
    let in_table = table_for_model_name(schema, &edge.in_model, naming);
    let out_table = table_for_model_name(schema, &edge.out_model, naming);
    out.push(format!("export type {} = {{", edge.name));
    out.push(format!("  id: RecordId<\"{}\">;", edge.table_name(naming.convention())));
    out.push(format!("  in: RecordId<\"{in_table}\">;"));
    out.push(format!("  out: RecordId<\"{out_table}\">;"));
    for field in edge.fields.iter().filter(|f| !f.name.contains('.')) {
        let ts = map_scalar_or_object(None, &field.field_type, field, naming);
        let optional = if field.optional { "?" } else { "" };
        let name = naming.field_name(field);
        out.push(format!("  {name}{optional}: {ts};"));
    }
    out.push("};".to_owned());
    out.push(String::new());
}

fn emit_edge_selected(
    out: &mut Vec<String>,
    _schema: &DatabaseSchema,
    edge: &Edge,
    naming: &NamingContext<'_>,
) {
    out.push(format!("export type {}Selected = {{", edge.name));
    out.push(format!("  id: RecordId<\"{}\">;", edge.table_name(naming.convention())));
    out.push(format!("  in: {}Selected;", edge.in_model));
    out.push(format!("  out: {}Selected;", edge.out_model));
    for field in edge.fields.iter().filter(|f| !f.name.contains('.')) {
        let ts = map_scalar_or_object(None, &field.field_type, field, naming);
        let optional = if field.optional { "?" } else { "" };
        let name = naming.field_name(field);
        out.push(format!("  {name}{optional}: {ts};"));
    }
    out.push("};".to_owned());
    out.push(String::new());
}

fn emit_edge_inputs(
    out: &mut Vec<String>,
    schema: &DatabaseSchema,
    edge: &Edge,
    naming: &NamingContext<'_>,
) {
    let in_table = table_for_model_name(schema, &edge.in_model, naming);
    let out_table = table_for_model_name(schema, &edge.out_model, naming);
    out.push(format!("export type {}CreateInput = {{", edge.name));
    out.push(format!("  in: RecordId<\"{in_table}\"> | string;"));
    out.push(format!("  out: RecordId<\"{out_table}\"> | string;"));
    for field in edge.fields.iter().filter(|f| !f.name.contains('.')) {
        let ts = map_scalar_or_object(None, &field.field_type, field, naming);
        let optional = if field.optional { "?" } else { "" };
        let name = naming.field_name(field);
        out.push(format!("  {name}{optional}: {ts};"));
    }
    out.push("};".to_owned());
    out.push(String::new());

    out.push(format!("export type {}UpdateInput = {{", edge.name));
    out.push(format!("  in?: RecordId<\"{in_table}\"> | string;"));
    out.push(format!("  out?: RecordId<\"{out_table}\"> | string;"));
    for field in edge.fields.iter().filter(|f| !f.name.contains('.')) {
        let ts = map_scalar_or_object(None, &field.field_type, field, naming);
        let name = naming.field_name(field);
        out.push(format!("  {name}?: {ts};"));
    }
    out.push("};".to_owned());
    out.push(String::new());
}

fn emit_edge_select_payload(
    out: &mut Vec<String>,
    schema: &DatabaseSchema,
    edge: &Edge,
    naming: &NamingContext<'_>,
) {
    let in_table = table_for_model_name(schema, &edge.in_model, naming);
    let out_table = table_for_model_name(schema, &edge.out_model, naming);

    out.push(format!("export type {}Scalars = {{", edge.name));
    out.push(format!(
        "  id: RecordId<\"{}\">;",
        edge.table_name(naming.convention())
    ));
    out.push(format!("  in: RecordId<\"{in_table}\">;"));
    out.push(format!("  out: RecordId<\"{out_table}\">;"));
    for field in edge.fields.iter().filter(|f| !f.name.contains('.')) {
        let name = naming.field_name(field);
        let ts = map_scalar_or_object(None, &field.field_type, field, naming);
        out.push(format!("  {name}: {ts};"));
    }
    out.push("};".to_owned());
    out.push(String::new());

    out.push(format!("export type {}Select = {{", edge.name));
    out.push("  id?: boolean;".to_owned());
    out.push(format!("  in?: SelectArg<{}Select>;", edge.in_model));
    out.push(format!("  out?: SelectArg<{}Select>;", edge.out_model));
    for field in edge.fields.iter().filter(|f| !f.name.contains('.')) {
        let name = naming.field_name(field);
        out.push(format!("  {name}?: boolean;"));
    }
    out.push("};".to_owned());
    out.push(String::new());

    out.push(format!("type {}InField<V> = V extends true", edge.name));
    out.push(format!("  ? {}", edge.in_model));
    out.push(format!(
        "  : V extends {{ select?: infer N extends {}Select | undefined }}",
        edge.in_model
    ));
    out.push(format!("    ? {}GetPayload<N>", edge.in_model));
    out.push("    : never;".to_owned());
    out.push(String::new());

    out.push(format!("type {}OutField<V> = V extends true", edge.name));
    out.push(format!("  ? {}", edge.out_model));
    out.push(format!(
        "  : V extends {{ select?: infer N extends {}Select | undefined }}",
        edge.out_model
    ));
    out.push(format!("    ? {}GetPayload<N>", edge.out_model));
    out.push("    : never;".to_owned());
    out.push(String::new());

    out.push(format!(
        "export type {}GetPayload<S extends {}Select | undefined = undefined> =",
        edge.name, edge.name
    ));
    out.push("  [S] extends [undefined]".to_owned());
    out.push(format!("    ? {}", edge.name));
    out.push("    : {".to_owned());
    out.push(
        "        [K in keyof S as S[K] extends false | undefined ? never : K]-?:"
            .to_owned(),
    );
    out.push(format!("          K extends \"in\" ? {}InField<S[K]>", edge.name));
    out.push(format!("          : K extends \"out\" ? {}OutField<S[K]>", edge.name));
    out.push(format!("          : K extends keyof {}Scalars ? {}Scalars[K]", edge.name, edge.name));
    out.push("          : never;".to_owned());
    out.push("      };".to_owned());
    out.push(String::new());
}

fn relation_select_type_name(schema: &DatabaseSchema, field: &Field) -> String {
    if let Some(relation) = &field.relation_name {
        return format!("{}Select", resolve_edge_type_name(schema, relation));
    }
    let target = field
        .link_target
        .as_deref()
        .or_else(|| field.field_type.link_model_name())
        .unwrap_or("unknown");
    format!("{target}Select")
}

fn relation_payload_parts(schema: &DatabaseSchema, field: &Field) -> (String, String, bool) {
    let list = field.is_list_link() || matches!(field.field_type, FieldType::Array(_));
    if let Some(relation) = &field.relation_name {
        let edge = resolve_edge_type_name(schema, relation);
        return (edge.clone(), format!("{edge}Select"), list);
    }
    let target = field
        .link_target
        .as_deref()
        .or_else(|| field.field_type.link_model_name())
        .unwrap_or("unknown")
        .to_owned();
    (target.clone(), format!("{target}Select"), list)
}

fn pascal_case(name: &str) -> String {
    let mut chars = name.chars();
    chars.next().map_or_else(String::new, |first| {
        first.to_uppercase().collect::<String>() + chars.as_str()
    })
}

fn should_omit_on_record(field: &Field) -> bool {
    field.is_computed_link() || field.relation_name.is_some()
}

fn map_model_field_record(
    schema: &DatabaseSchema,
    model: &Model,
    field: &Field,
    naming: &NamingContext<'_>,
) -> String {
    if field.is_id {
        if let Some(model_name) = field.field_type.link_model_name() {
            let table = table_for_model_name(schema, model_name, naming);
            return format!("RecordId<\"{table}\">");
        }
        if let FieldType::RecordId(target) = &field.field_type {
            let table = table_for_model_name(schema, target, naming);
            return format!("RecordId<\"{table}\">");
        }
    }

    if field.is_stored_link() {
        return map_link_as_record_id(schema, field, naming);
    }

    map_scalar_or_object(Some((schema, model)), &field.field_type, field, naming)
}

fn map_model_field_selected(
    schema: &DatabaseSchema,
    model: &Model,
    field: &Field,
    naming: &NamingContext<'_>,
) -> String {
    if field.is_id {
        return map_model_field_record(schema, model, field, naming);
    }

    if let Some(relation) = &field.relation_name {
        let edge_name = resolve_edge_type_name(schema, relation);
        let list = field.is_list_link() || matches!(field.field_type, FieldType::Array(_));
        return if list {
            format!("{edge_name}Selected[]")
        } else {
            format!("{edge_name}Selected")
        };
    }

    if field.is_link() {
        let target = field
            .link_target
            .as_deref()
            .or_else(|| field.field_type.link_model_name())
            .unwrap_or("unknown");
        let list = field.is_list_link();
        return if list {
            format!("{target}Selected[]")
        } else {
            format!("{target}Selected")
        };
    }

    map_scalar_or_object(Some((schema, model)), &field.field_type, field, naming)
}

fn map_link_as_record_id(schema: &DatabaseSchema, field: &Field, naming: &NamingContext<'_>) -> String {
    let target = field
        .link_target
        .as_deref()
        .or_else(|| field.field_type.link_model_name())
        .unwrap_or("unknown");
    let table = table_for_model_name(schema, target, naming);
    if field.is_list_link() {
        format!("RecordId<\"{table}\">[]")
    } else {
        format!("RecordId<\"{table}\">")
    }
}

fn map_scalar_or_object(
    ctx: Option<(&DatabaseSchema, &Model)>,
    field_type: &FieldType,
    field: &Field,
    naming: &NamingContext<'_>,
) -> String {
    match field_type {
        FieldType::Object => {
            if let Some((schema, model)) = ctx
                && let Some(name) = resolve_named_object_type(schema, model, field)
            {
                return name;
            }
            "Record<string, unknown>".to_owned()
        }
        FieldType::Model(name) if field.link_target.is_none() && field.relation_name.is_none() => {
            name.clone()
        }
        other => map_object_field_type(other, naming),
    }
}

fn resolve_named_object_type(
    schema: &DatabaseSchema,
    model: &Model,
    parent: &Field,
) -> Option<String> {
    let prefix = format!("{}.", parent.name);
    let nested: Vec<&Field> = model
        .fields
        .iter()
        .filter(|field| field.name.starts_with(&prefix))
        .collect();

    schema.object_types.iter().find_map(|object_type| {
        if object_type.flexible != parent.flexible {
            return None;
        }
        if object_type.fields.len() != nested.len() {
            return None;
        }
        let matched = object_type.fields.iter().all(|candidate| {
            nested.iter().any(|field| {
                field.name == format!("{}.{}", parent.name, candidate.name)
                    && field.field_type == candidate.field_type
                    && field.optional == candidate.optional
            })
        });
        matched.then(|| object_type.name.clone())
    })
}

fn map_object_field_type(field_type: &FieldType, naming: &NamingContext<'_>) -> String {
    match field_type {
        FieldType::String => "string".to_owned(),
        FieldType::Int | FieldType::Float => "number".to_owned(),
        FieldType::Bool => "boolean".to_owned(),
        FieldType::Datetime => "Date".to_owned(),
        FieldType::Object => "Record<string, unknown>".to_owned(),
        FieldType::Array(inner) => format!("{}[]", map_object_field_type(inner, naming)),
        FieldType::RecordId(name) => {
            let table = naming.convention().tables.apply(name);
            format!("RecordId<\"{table}\">")
        }
        FieldType::Model(name) => name.clone(),
        FieldType::Custom(value) => value.clone(),
    }
}

fn table_for_model_name(schema: &DatabaseSchema, model_name: &str, naming: &NamingContext<'_>) -> String {
    schema
        .models
        .iter()
        .find(|model| model.name == model_name)
        .map_or_else(
            || naming.convention().tables.apply(model_name),
            |model| model.table_name(naming.convention()),
        )
}

fn resolve_edge_type_name(schema: &DatabaseSchema, relation_name: &str) -> String {
    schema
        .edges
        .iter()
        .find(|edge| {
            edge.name == relation_name
                || edge.table_name(&schema.naming) == *relation_name
                || edge.attributes.get("map").is_some_and(|mapped| mapped == relation_name)
        })
        .map_or_else(|| relation_name.to_owned(), |edge| edge.name.clone())
}

fn client_key(name: &str) -> String {
    let mut chars = name.chars();
    chars.next().map_or_else(String::new, |first| {
        first.to_lowercase().collect::<String>() + chars.as_str()
    })
}

fn query_fn_name(name: &str) -> String {
    if name.ends_with('s') {
        format!("query{name}")
    } else {
        format!("query{name}s")
    }
}

fn query_related_fn_name(name: &str) -> String {
    format!("{}Related", query_fn_name(name))
}

fn emit_tables_const(out: &mut Vec<String>, schema: &DatabaseSchema, naming: &NamingContext<'_>) {
    out.push("export const Tables = {".to_owned());
    for model in &schema.models {
        out.push(format!(
            "  {}: \"{}\",",
            model.name,
            model.table_name(naming.convention())
        ));
    }
    for edge in &schema.edges {
        out.push(format!(
            "  {}: \"{}\",",
            edge.name,
            edge.table_name(naming.convention())
        ));
    }
    out.push("} as const;".to_owned());
    out.push(String::new());
}

fn emit_select_meta_registry(
    out: &mut Vec<String>,
    schema: &DatabaseSchema,
    naming: &NamingContext<'_>,
) {
    out.push("export type FieldSelectMeta =".to_owned());
    out.push(
        "  | { kind: \"scalar\"; filter: \"string\" | \"number\" | \"boolean\" | \"datetime\" | \"json\" | \"array\" | \"id\" }"
            .to_owned(),
    );
    out.push(
        "  | { kind: \"stored\" | \"computed\"; targetTable: string; list: boolean }".to_owned(),
    );
    out.push(
        "  | { kind: \"edge\"; edgeTable: string; dir: \"out\" | \"in\"; list: boolean };"
            .to_owned(),
    );
    out.push(String::new());
    out.push(
        "export const SelectMetaByTable: Record<string, Record<string, FieldSelectMeta>> = {"
            .to_owned(),
    );

    for model in &schema.models {
        let table = model.table_name(naming.convention());
        out.push(format!("  \"{table}\": {{"));
        for field in model.fields.iter().filter(|f| !f.name.contains('.')) {
            let name = naming.field_name(field);
            if let Some(relation) = &field.relation_name {
                let edge_name = resolve_edge_type_name(schema, relation);
                let Some(edge) = schema.edges.iter().find(|e| e.name == edge_name) else {
                    continue;
                };
                let edge_table = edge.table_name(naming.convention());
                let dir = if edge.in_model == model.name {
                    "out"
                } else if edge.out_model == model.name {
                    "in"
                } else {
                    continue;
                };
                let list = field.is_list_link()
                    || matches!(field.field_type, FieldType::Array(_));
                out.push(format!(
                    "    {name}: {{ kind: \"edge\", edgeTable: \"{edge_table}\", dir: \"{dir}\", list: {list} }},"
                ));
            } else if field.is_link() {
                let target = field
                    .link_target
                    .as_deref()
                    .or_else(|| field.field_type.link_model_name())
                    .unwrap_or("unknown");
                let target_table = table_for_model_name(schema, target, naming);
                let kind = if field.is_computed_link() {
                    "computed"
                } else {
                    "stored"
                };
                let list = field.is_list_link();
                out.push(format!(
                    "    {name}: {{ kind: \"{kind}\", targetTable: \"{target_table}\", list: {list} }},"
                ));
            } else if !should_omit_on_record(field) {
                let filter = scalar_filter_kind(&field.field_type, field.is_id);
                out.push(format!(
                    "    {name}: {{ kind: \"scalar\", filter: \"{filter}\" }},"
                ));
            }
        }
        out.push("  },".to_owned());
    }

    for edge in &schema.edges {
        let table = edge.table_name(naming.convention());
        let in_table = table_for_model_name(schema, &edge.in_model, naming);
        let out_table = table_for_model_name(schema, &edge.out_model, naming);
        out.push(format!("  \"{table}\": {{"));
        out.push(
            "    id: { kind: \"scalar\", filter: \"id\" },".to_owned(),
        );
        out.push(format!(
            "    in: {{ kind: \"stored\", targetTable: \"{in_table}\", list: false }},"
        ));
        out.push(format!(
            "    out: {{ kind: \"stored\", targetTable: \"{out_table}\", list: false }},"
        ));
        for field in edge.fields.iter().filter(|f| !f.name.contains('.')) {
            let name = naming.field_name(field);
            let filter = scalar_filter_kind(&field.field_type, false);
            out.push(format!(
                "    {name}: {{ kind: \"scalar\", filter: \"{filter}\" }},"
            ));
        }
        out.push("  },".to_owned());
    }

    out.push("};".to_owned());
    out.push(String::new());
}

fn emit_record_id_helpers(out: &mut Vec<String>) {
    out.push("export function recordId<Table extends string>(".to_owned());
    out.push("  table: Table,".to_owned());
    out.push("  key: string,".to_owned());
    out.push("): RecordId<Table> {".to_owned());
    out.push("  return `${table}:${key}` as RecordId<Table>;".to_owned());
    out.push("}".to_owned());
    out.push(String::new());
    out.push("export function parseRecordId(".to_owned());
    out.push("  value: string,".to_owned());
    out.push("): { table: string; key: string } | null {".to_owned());
    out.push("  const i = value.indexOf(\":\");".to_owned());
    out.push("  if (i <= 0) return null;".to_owned());
    out.push("  return { table: value.slice(0, i), key: value.slice(i + 1) };".to_owned());
    out.push("}".to_owned());
    out.push(String::new());
    out.push("export function asRecordId<Table extends string>(".to_owned());
    out.push("  table: Table,".to_owned());
    out.push("  value: string,".to_owned());
    out.push("): RecordId<Table> {".to_owned());
    out.push("  return (value.includes(\":\") ? value : `${table}:${value}`) as RecordId<Table>;".to_owned());
    out.push("}".to_owned());
    out.push(String::new());
    out.push("function normalizeThing(table: string, id: string): string {".to_owned());
    out.push("  return id.includes(\":\") ? id : `${table}:${id}`;".to_owned());
    out.push("}".to_owned());
    out.push(String::new());
    out.push("async function firstRow<T>(result: unknown): Promise<T | undefined> {".to_owned());
    out.push("  if (Array.isArray(result)) {".to_owned());
    out.push("    const first = result[0];".to_owned());
    out.push("    if (Array.isArray(first)) return first[0] as T | undefined;".to_owned());
    out.push("    return first as T | undefined;".to_owned());
    out.push("  }".to_owned());
    out.push("  return result as T | undefined;".to_owned());
    out.push("}".to_owned());
    out.push(String::new());
    out.push("async function asRows<T>(result: unknown): Promise<T[]> {".to_owned());
    out.push("  if (Array.isArray(result)) {".to_owned());
    out.push("    const first = result[0];".to_owned());
    out.push("    if (Array.isArray(first)) return first as T[];".to_owned());
    out.push("    return result as T[];".to_owned());
    out.push("  }".to_owned());
    out.push("  if (result == null) return [];".to_owned());
    out.push("  return [result as T];".to_owned());
    out.push("}".to_owned());
    out.push(String::new());
    out.push("function selectedFetchKeys(select: Record<string, boolean | undefined> | undefined): string[] {".to_owned());
    out.push("  if (!select) return [];".to_owned());
    out.push("  return Object.entries(select)".to_owned());
    out.push("    .filter(([, enabled]) => enabled)".to_owned());
    out.push("    .map(([key]) => key);".to_owned());
    out.push("}".to_owned());
    out.push(String::new());
}

fn emit_surreal_like(out: &mut Vec<String>) {
    out.push("/** Core Surreal operations used by generated helpers (session or open transaction). */".to_owned());
    out.push("export type SurrealOpsLike = {".to_owned());
    out.push(
        "  query<T = unknown>(sql: string, vars?: Record<string, unknown>): Promise<T>;"
            .to_owned(),
    );
    out.push("  select<T = unknown>(thing: string): Promise<T>;".to_owned());
    out.push(
        "  create<T = unknown>(thing: string, data?: Record<string, unknown>): Promise<T>;"
            .to_owned(),
    );
    out.push(
        "  merge<T = unknown>(thing: string, data?: Record<string, unknown>): Promise<T>;"
            .to_owned(),
    );
    out.push("  delete<T = unknown>(thing: string): Promise<T>;".to_owned());
    out.push("};".to_owned());
    out.push(String::new());
    out.push("/** Interactive transaction handle (WebSocket / embedded). */".to_owned());
    out.push("export type SurrealTransactionLike = SurrealOpsLike & {".to_owned());
    out.push("  commit(): Promise<void>;".to_owned());
    out.push("  cancel(): Promise<void>;".to_owned());
    out.push("};".to_owned());
    out.push(String::new());
    out.push("/** Session connection; `beginTransaction` is required for `$transaction`. */".to_owned());
    out.push("export type SurrealLike = SurrealOpsLike & {".to_owned());
    out.push("  beginTransaction(): Promise<SurrealTransactionLike>;".to_owned());
    out.push("};".to_owned());
    out.push(String::new());
}

fn emit_shared_runtime(out: &mut Vec<String>) {
    out.push("async function selectRecord<T>(".to_owned());
    out.push("  db: SurrealOpsLike,".to_owned());
    out.push("  table: string,".to_owned());
    out.push("  id: string,".to_owned());
    out.push("): Promise<T | undefined> {".to_owned());
    out.push("  const thing = normalizeThing(table, id);".to_owned());
    out.push("  return firstRow<T>(await db.select(thing));".to_owned());
    out.push("}".to_owned());
    out.push(String::new());

    out.push("async function selectRecordRelated<T>(".to_owned());
    out.push("  db: SurrealOpsLike,".to_owned());
    out.push("  table: string,".to_owned());
    out.push("  id: string,".to_owned());
    out.push("  fetch: string[],".to_owned());
    out.push("): Promise<T | undefined> {".to_owned());
    out.push("  const thing = normalizeThing(table, id);".to_owned());
    out.push("  if (fetch.length === 0) return firstRow<T>(await db.select(thing));".to_owned());
    out.push(
        "  const row = await db.query(`SELECT * FROM type::record($thing) FETCH ${fetch.join(\", \")}`, { thing });"
            .to_owned(),
    );
    out.push("  return firstRow<T>(row);".to_owned());
    out.push("}".to_owned());
    out.push(String::new());

    out.push("async function createRecord<T>(".to_owned());
    out.push("  db: SurrealOpsLike,".to_owned());
    out.push("  table: string,".to_owned());
    out.push("  data: Record<string, unknown>,".to_owned());
    out.push("): Promise<T> {".to_owned());
    out.push("  const created = await firstRow<T>(await db.create(table, data));".to_owned());
    out.push("  if (!created) throw new Error(`create ${table} returned no row`);".to_owned());
    out.push("  return created;".to_owned());
    out.push("}".to_owned());
    out.push(String::new());

    out.push("async function updateRecord<T>(".to_owned());
    out.push("  db: SurrealOpsLike,".to_owned());
    out.push("  table: string,".to_owned());
    out.push("  id: string,".to_owned());
    out.push("  data: Record<string, unknown>,".to_owned());
    out.push("): Promise<T | undefined> {".to_owned());
    out.push("  const thing = normalizeThing(table, id);".to_owned());
    out.push("  return firstRow<T>(await db.merge(thing, data));".to_owned());
    out.push("}".to_owned());
    out.push(String::new());

    out.push("async function deleteRecord(".to_owned());
    out.push("  db: SurrealOpsLike,".to_owned());
    out.push("  table: string,".to_owned());
    out.push("  id: string,".to_owned());
    out.push("): Promise<void> {".to_owned());
    out.push("  await db.delete(normalizeThing(table, id));".to_owned());
    out.push("}".to_owned());
    out.push(String::new());

    out.push("async function queryRows<T>(".to_owned());
    out.push("  db: SurrealOpsLike,".to_owned());
    out.push("  sql: string,".to_owned());
    out.push("  vars?: Record<string, unknown>,".to_owned());
    out.push("): Promise<T[]> {".to_owned());
    out.push("  return asRows<T>(await db.query(sql, vars));".to_owned());
    out.push("}".to_owned());
    out.push(String::new());

    out.push("function projectField(".to_owned());
    out.push("  key: string,".to_owned());
    out.push("  value: unknown,".to_owned());
    out.push("  fieldMeta: FieldSelectMeta,".to_owned());
    out.push("  allMeta: Record<string, Record<string, FieldSelectMeta>>,".to_owned());
    out.push("): string | null {".to_owned());
    out.push("  if (value === false || value == null) return null;".to_owned());
    out.push("  if (fieldMeta.kind === \"scalar\") return key;".to_owned());
    out.push("  if (value === true) {".to_owned());
    out.push("    if (fieldMeta.kind === \"edge\") {".to_owned());
    out.push(
        "      const arrow = fieldMeta.dir === \"out\" ? `->${fieldMeta.edgeTable}` : `<-${fieldMeta.edgeTable}`;"
            .to_owned(),
    );
    out.push("      return `${arrow}.* AS ${key}`;".to_owned());
    out.push("    }".to_owned());
    out.push("    return `${key}.*`;".to_owned());
    out.push("  }".to_owned());
    out.push("  if (typeof value === \"object\" && value !== null && \"select\" in value) {".to_owned());
    out.push(
        "    const nestedSelect = (value as { select?: Record<string, unknown> }).select;"
            .to_owned(),
    );
    out.push("    const nestedTable =".to_owned());
    out.push(
        "      fieldMeta.kind === \"edge\" ? fieldMeta.edgeTable : fieldMeta.targetTable;"
            .to_owned(),
    );
    out.push(
        "    const nested = buildProjection(nestedSelect, nestedTable, allMeta);"
            .to_owned(),
    );
    out.push("    if (fieldMeta.kind === \"edge\") {".to_owned());
    out.push(
        "      const arrow = fieldMeta.dir === \"out\" ? `->${fieldMeta.edgeTable}` : `<-${fieldMeta.edgeTable}`;"
            .to_owned(),
    );
    out.push("      return `${arrow}.{ ${nested} } AS ${key}`;".to_owned());
    out.push("    }".to_owned());
    out.push("    return `${key}.{ ${nested} }`;".to_owned());
    out.push("  }".to_owned());
    out.push("  return null;".to_owned());
    out.push("}".to_owned());
    out.push(String::new());

    out.push("function buildProjection(".to_owned());
    out.push("  select: Record<string, unknown> | undefined,".to_owned());
    out.push("  table: string,".to_owned());
    out.push(
        "  allMeta: Record<string, Record<string, FieldSelectMeta>> = SelectMetaByTable,"
            .to_owned(),
    );
    out.push("): string {".to_owned());
    out.push("  if (!select) return \"*\";".to_owned());
    out.push("  const meta = allMeta[table] ?? {};".to_owned());
    out.push("  const parts: string[] = [];".to_owned());
    out.push("  for (const [key, value] of Object.entries(select)) {".to_owned());
    out.push("    const fieldMeta = meta[key];".to_owned());
    out.push("    if (!fieldMeta) continue;".to_owned());
    out.push("    const part = projectField(key, value, fieldMeta, allMeta);".to_owned());
    out.push("    if (part) parts.push(part);".to_owned());
    out.push("  }".to_owned());
    out.push("  return parts.length === 0 ? \"*\" : parts.join(\", \");".to_owned());
    out.push("}".to_owned());
    out.push(String::new());

    emit_build_where(out);

    out.push("function uniqueWhereId(where: Record<string, unknown> | undefined): string | undefined {".to_owned());
    out.push("  if (!where) return undefined;".to_owned());
    out.push("  const keys = Object.keys(where).filter((key) => where[key] !== undefined);".to_owned());
    out.push("  if (keys.length !== 1 || keys[0] !== \"id\") return undefined;".to_owned());
    out.push("  const id = where.id;".to_owned());
    out.push("  if (typeof id === \"string\") return id;".to_owned());
    out.push("  if (id && typeof id === \"object\" && !Array.isArray(id) && \"equals\" in id) {".to_owned());
    out.push("    const equals = (id as { equals?: unknown }).equals;".to_owned());
    out.push("    return typeof equals === \"string\" ? equals : undefined;".to_owned());
    out.push("  }".to_owned());
    out.push("  return undefined;".to_owned());
    out.push("}".to_owned());
    out.push(String::new());

    out.push("async function findUniqueRecord<T>(".to_owned());
    out.push("  db: SurrealOpsLike,".to_owned());
    out.push("  table: string,".to_owned());
    out.push("  args: {".to_owned());
    out.push("    where: Record<string, unknown>;".to_owned());
    out.push("    select?: Record<string, unknown>;".to_owned());
    out.push("    vars?: Record<string, unknown>;".to_owned());
    out.push("  },".to_owned());
    out.push("): Promise<T | undefined> {".to_owned());
    out.push("  const idOnly = uniqueWhereId(args.where);".to_owned());
    out.push("  if (idOnly !== undefined) {".to_owned());
    out.push("    if (!args.select) return selectRecord<T>(db, table, idOnly);".to_owned());
    out.push("    const thing = normalizeThing(table, idOnly);".to_owned());
    out.push("    const projection = buildProjection(args.select, table);".to_owned());
    out.push(
        "    const row = await db.query(`SELECT ${projection} FROM type::record($thing)`, { thing });"
            .to_owned(),
    );
    out.push("    return firstRow<T>(row);".to_owned());
    out.push("  }".to_owned());
    out.push(
        "  const projection = args.select ? buildProjection(args.select, table) : \"*\";"
            .to_owned(),
    );
    out.push("  const vars: Record<string, unknown> = { ...(args.vars ?? {}) };".to_owned());
    out.push(
        "  const whereClause = buildWhere(args.where, table, SelectMetaByTable, { vars, n: 0 });"
            .to_owned(),
    );
    out.push("  if (!whereClause) return undefined;".to_owned());
    out.push(
        "  const rows = await queryRows<T>(db, `SELECT ${projection} FROM ${table} WHERE ${whereClause} LIMIT 1`, vars);"
            .to_owned(),
    );
    out.push("  return rows[0];".to_owned());
    out.push("}".to_owned());
    out.push(String::new());

    emit_build_order_by(out);

    out.push("async function findManyRecords<T>(".to_owned());
    out.push("  db: SurrealOpsLike,".to_owned());
    out.push("  table: string,".to_owned());
    out.push("  args: {".to_owned());
    out.push("    select?: Record<string, unknown>;".to_owned());
    out.push("    where?: Record<string, unknown>;".to_owned());
    out.push("    orderBy?: Record<string, unknown> | Record<string, unknown>[];".to_owned());
    out.push("    take?: number;".to_owned());
    out.push("    skip?: number;".to_owned());
    out.push("    whereSql?: string;".to_owned());
    out.push("    vars?: Record<string, unknown>;".to_owned());
    out.push("  } = {},".to_owned());
    out.push("): Promise<T[]> {".to_owned());
    out.push(
        "  const projection = args.select ? buildProjection(args.select, table) : \"*\";"
            .to_owned(),
    );
    out.push("  const vars: Record<string, unknown> = { ...(args.vars ?? {}) };".to_owned());
    out.push("  let sql: string;".to_owned());
    out.push("  if (args.where) {".to_owned());
    out.push(
        "    const whereClause = buildWhere(args.where, table, SelectMetaByTable, { vars, n: 0 });"
            .to_owned(),
    );
    out.push("    sql = whereClause".to_owned());
    out.push(
        "      ? `SELECT ${projection} FROM ${table} WHERE ${whereClause}`"
            .to_owned(),
    );
    out.push("      : `SELECT ${projection} FROM ${table}`;".to_owned());
    out.push("  } else if (args.whereSql) {".to_owned());
    out.push(
        "    sql = args.whereSql.replace(/^\\s*SELECT\\s+\\*/i, `SELECT ${projection}`);"
            .to_owned(),
    );
    out.push("  } else {".to_owned());
    out.push("    sql = `SELECT ${projection} FROM ${table}`;".to_owned());
    out.push("  }".to_owned());
    out.push("  const orderClause = buildOrderBy(args.orderBy, table);".to_owned());
    out.push("  if (orderClause) sql = `${sql} ${orderClause}`;".to_owned());
    out.push("  sql = appendLimitStart(sql, args.take, args.skip, vars);".to_owned());
    out.push("  return queryRows<T>(db, sql, vars);".to_owned());
    out.push("}".to_owned());
    out.push(String::new());

    out.push("function assertNonEmptyWhere(".to_owned());
    out.push("  where: Record<string, unknown> | undefined,".to_owned());
    out.push("  op: string,".to_owned());
    out.push("  table: string,".to_owned());
    out.push("): void {".to_owned());
    out.push("  if (!where) throw new Error(`${op} ${table}: where must not be empty`);".to_owned());
    out.push(
        "  const keys = Object.keys(where).filter((key) => where[key] !== undefined);"
            .to_owned(),
    );
    out.push("  if (keys.length === 0) throw new Error(`${op} ${table}: where must not be empty`);".to_owned());
    out.push("}".to_owned());
    out.push(String::new());

    out.push("function projectRow(".to_owned());
    out.push("  row: Record<string, unknown>,".to_owned());
    out.push("  select: Record<string, unknown> | undefined,".to_owned());
    out.push("): Record<string, unknown> {".to_owned());
    out.push("  if (!select) return row;".to_owned());
    out.push("  const out: Record<string, unknown> = {};".to_owned());
    out.push("  for (const [key, value] of Object.entries(select)) {".to_owned());
    out.push("    if (value === false || value == null) continue;".to_owned());
    out.push("    if (value === true) {".to_owned());
    out.push("      out[key] = row[key];".to_owned());
    out.push("      continue;".to_owned());
    out.push("    }".to_owned());
    out.push("    if (typeof value === \"object\" && value !== null && \"select\" in value) {".to_owned());
    out.push(
        "      const nestedSelect = (value as { select?: Record<string, unknown> }).select;"
            .to_owned(),
    );
    out.push("      const nested = row[key];".to_owned());
    out.push("      if (Array.isArray(nested)) {".to_owned());
    out.push("        out[key] = nested.map((item) =>".to_owned());
    out.push("          item && typeof item === \"object\"".to_owned());
    out.push(
        "            ? projectRow(item as Record<string, unknown>, nestedSelect)"
            .to_owned(),
    );
    out.push("            : item,".to_owned());
    out.push("        );".to_owned());
    out.push("      } else if (nested && typeof nested === \"object\") {".to_owned());
    out.push(
        "        out[key] = projectRow(nested as Record<string, unknown>, nestedSelect);"
            .to_owned(),
    );
    out.push("      } else {".to_owned());
    out.push("        out[key] = nested;".to_owned());
    out.push("      }".to_owned());
    out.push("    }".to_owned());
    out.push("  }".to_owned());
    out.push("  return out;".to_owned());
    out.push("}".to_owned());
    out.push(String::new());

    out.push("async function createManyVia<T extends { id?: unknown }>(".to_owned());
    out.push("  db: SurrealOpsLike,".to_owned());
    out.push("  table: string,".to_owned());
    out.push("  args: { data: Record<string, unknown>[]; select?: Record<string, unknown> },".to_owned());
    out.push("  createOne: (data: Record<string, unknown>) => Promise<T>,".to_owned());
    out.push("): Promise<{ count: number } | T[]> {".to_owned());
    out.push("  if (!args.select) {".to_owned());
    out.push("    for (const data of args.data) {".to_owned());
    out.push("      await createOne(data);".to_owned());
    out.push("    }".to_owned());
    out.push("    return { count: args.data.length };".to_owned());
    out.push("  }".to_owned());
    out.push("  const rows: T[] = [];".to_owned());
    out.push("  for (const data of args.data) {".to_owned());
    out.push("    const created = await createOne(data);".to_owned());
    out.push("    const id = created?.id != null ? String(created.id) : undefined;".to_owned());
    out.push(
        "    if (id === undefined) throw new Error(`createMany ${table}: created row missing id`);"
            .to_owned(),
    );
    out.push(
        "    const projected = await findUniqueRecord<T>(db, table, { where: { id }, select: args.select });"
            .to_owned(),
    );
    out.push(
        "    if (!projected) throw new Error(`createMany ${table}: could not reload ${id}`);"
            .to_owned(),
    );
    out.push("    rows.push(projected);".to_owned());
    out.push("  }".to_owned());
    out.push("  return rows;".to_owned());
    out.push("}".to_owned());
    out.push(String::new());

    out.push("async function updateManyRecords<T>(".to_owned());
    out.push("  db: SurrealOpsLike,".to_owned());
    out.push("  table: string,".to_owned());
    out.push("  args: {".to_owned());
    out.push("    where: Record<string, unknown>;".to_owned());
    out.push("    data: Record<string, unknown>;".to_owned());
    out.push("    select?: Record<string, unknown>;".to_owned());
    out.push("  },".to_owned());
    out.push("): Promise<{ count: number } | T[]> {".to_owned());
    out.push("  assertNonEmptyWhere(args.where, \"updateMany\", table);".to_owned());
    out.push("  const vars: Record<string, unknown> = { __data: args.data };".to_owned());
    out.push(
        "  const whereClause = buildWhere(args.where, table, SelectMetaByTable, { vars, n: 0 });"
            .to_owned(),
    );
    out.push(
        "  if (!whereClause) throw new Error(`updateMany ${table}: where must not be empty`);"
            .to_owned(),
    );
    out.push(
        "  const ret = args.select ? buildProjection(args.select, table) : \"AFTER\";"
            .to_owned(),
    );
    out.push(
        "  const rows = await queryRows<T>(db, `UPDATE ${table} MERGE $__data WHERE ${whereClause} RETURN ${ret}`, vars);"
            .to_owned(),
    );
    out.push("  if (args.select) return rows;".to_owned());
    out.push("  return { count: rows.length };".to_owned());
    out.push("}".to_owned());
    out.push(String::new());

    out.push("async function deleteManyRecords<T>(".to_owned());
    out.push("  db: SurrealOpsLike,".to_owned());
    out.push("  table: string,".to_owned());
    out.push("  args: {".to_owned());
    out.push("    where: Record<string, unknown>;".to_owned());
    out.push("    select?: Record<string, unknown>;".to_owned());
    out.push("  },".to_owned());
    out.push("): Promise<{ count: number } | T[]> {".to_owned());
    out.push("  assertNonEmptyWhere(args.where, \"deleteMany\", table);".to_owned());
    out.push("  const vars: Record<string, unknown> = {};".to_owned());
    out.push(
        "  const whereClause = buildWhere(args.where, table, SelectMetaByTable, { vars, n: 0 });"
            .to_owned(),
    );
    out.push(
        "  if (!whereClause) throw new Error(`deleteMany ${table}: where must not be empty`);"
            .to_owned(),
    );
    out.push(
        "  const rows = await queryRows<Record<string, unknown>>(db, `DELETE ${table} WHERE ${whereClause} RETURN BEFORE`, vars);"
            .to_owned(),
    );
    out.push("  if (args.select) {".to_owned());
    out.push("    return rows.map((row) => projectRow(row, args.select) as T);".to_owned());
    out.push("  }".to_owned());
    out.push("  return { count: rows.length };".to_owned());
    out.push("}".to_owned());
    out.push(String::new());

    out.push("async function upsertRecord<T extends { id?: unknown }>(".to_owned());
    out.push("  db: SurrealOpsLike,".to_owned());
    out.push("  table: string,".to_owned());
    out.push("  args: {".to_owned());
    out.push("    where: Record<string, unknown>;".to_owned());
    out.push("    create: Record<string, unknown>;".to_owned());
    out.push("    update: Record<string, unknown>;".to_owned());
    out.push("    select?: Record<string, unknown>;".to_owned());
    out.push("  },".to_owned());
    out.push("  createOne: (data: Record<string, unknown>) => Promise<T> = (data) =>".to_owned());
    out.push("    createRecord<T>(db, table, data),".to_owned());
    out.push("): Promise<T> {".to_owned());
    out.push("  assertNonEmptyWhere(args.where, \"upsert\", table);".to_owned());
    out.push(
        "  const existing = await findUniqueRecord<{ id?: unknown }>(db, table, { where: args.where });"
            .to_owned(),
    );
    out.push("  if (existing?.id != null) {".to_owned());
    out.push(
        "    const updated = await updateRecord<T>(db, table, String(existing.id), args.update);"
            .to_owned(),
    );
    out.push(
        "    if (!updated) throw new Error(`upsert ${table}: update returned no row`);"
            .to_owned(),
    );
    out.push("    if (!args.select) return updated;".to_owned());
    out.push(
        "    const projected = await findUniqueRecord<T>(db, table, { where: { id: String(existing.id) }, select: args.select });"
            .to_owned(),
    );
    out.push(
        "    if (!projected) throw new Error(`upsert ${table}: could not reload after update`);"
            .to_owned(),
    );
    out.push("    return projected;".to_owned());
    out.push("  }".to_owned());
    out.push("  const created = await createOne(args.create);".to_owned());
    out.push("  if (!args.select) return created;".to_owned());
    out.push("  const id = created?.id != null ? String(created.id) : undefined;".to_owned());
    out.push(
        "  if (id === undefined) throw new Error(`upsert ${table}: created row missing id`);"
            .to_owned(),
    );
    out.push(
        "  const projected = await findUniqueRecord<T>(db, table, { where: { id }, select: args.select });"
            .to_owned(),
    );
    out.push(
        "  if (!projected) throw new Error(`upsert ${table}: could not reload after create`);"
            .to_owned(),
    );
    out.push("  return projected;".to_owned());
    out.push("}".to_owned());
    out.push(String::new());
}

fn emit_build_order_by(out: &mut Vec<String>) {
    out.push("function buildOrderBy(".to_owned());
    out.push("  orderBy: Record<string, unknown> | Record<string, unknown>[] | undefined,".to_owned());
    out.push("  table: string,".to_owned());
    out.push(
        "  allMeta: Record<string, Record<string, FieldSelectMeta>> = SelectMetaByTable,"
            .to_owned(),
    );
    out.push("): string {".to_owned());
    out.push("  if (!orderBy) return \"\";".to_owned());
    out.push("  const items = Array.isArray(orderBy) ? orderBy : [orderBy];".to_owned());
    out.push("  const meta = allMeta[table] ?? {};".to_owned());
    out.push("  const parts: string[] = [];".to_owned());
    out.push("  for (const item of items) {".to_owned());
    out.push("    if (!item || typeof item !== \"object\") continue;".to_owned());
    out.push("    for (const [key, value] of Object.entries(item)) {".to_owned());
    out.push("      if (value !== \"asc\" && value !== \"desc\") continue;".to_owned());
    out.push("      const fieldMeta = meta[key];".to_owned());
    out.push("      if (!fieldMeta || fieldMeta.kind !== \"scalar\") continue;".to_owned());
    out.push("      parts.push(`${key} ${value.toUpperCase()}`);".to_owned());
    out.push("    }".to_owned());
    out.push("  }".to_owned());
    out.push("  return parts.length === 0 ? \"\" : `ORDER BY ${parts.join(\", \")}`;".to_owned());
    out.push("}".to_owned());
    out.push(String::new());
    out.push("function appendLimitStart(".to_owned());
    out.push("  sql: string,".to_owned());
    out.push("  take: number | undefined,".to_owned());
    out.push("  skip: number | undefined,".to_owned());
    out.push("  vars: Record<string, unknown>,".to_owned());
    out.push("): string {".to_owned());
    out.push("  let out = sql;".to_owned());
    out.push("  if (take !== undefined) {".to_owned());
    out.push("    if (!Number.isFinite(take) || take < 0) throw new Error(\"take must be a non-negative number\");".to_owned());
    out.push("    vars.__take = Math.floor(take);".to_owned());
    out.push("    out = out + \" LIMIT $__take\";".to_owned());
    out.push("  }".to_owned());
    out.push("  if (skip !== undefined) {".to_owned());
    out.push("    if (!Number.isFinite(skip) || skip < 0) throw new Error(\"skip must be a non-negative number\");".to_owned());
    out.push("    vars.__skip = Math.floor(skip);".to_owned());
    out.push("    out = out + \" START $__skip\";".to_owned());
    out.push("  }".to_owned());
    out.push("  return out;".to_owned());
    out.push("}".to_owned());
    out.push(String::new());
}

fn emit_build_where(out: &mut Vec<String>) {
    out.push("type WhereBuildCtx = { vars: Record<string, unknown>; n: number };".to_owned());
    out.push(String::new());
    out.push("function nextWhereVar(ctx: WhereBuildCtx, value: unknown): string {".to_owned());
    out.push("  const key = `w${ctx.n++}`;".to_owned());
    out.push("  ctx.vars[key] = value;".to_owned());
    out.push("  return `$${key}`;".to_owned());
    out.push("}".to_owned());
    out.push(String::new());
    out.push("function isScalarFilterObject(value: unknown): value is Record<string, unknown> {".to_owned());
    out.push("  if (!value || typeof value !== \"object\" || Array.isArray(value)) return false;".to_owned());
    out.push("  return [\"equals\", \"in\", \"contains\", \"gt\", \"gte\", \"lt\", \"lte\"].some((k) =>".to_owned());
    out.push("    Object.prototype.hasOwnProperty.call(value, k),".to_owned());
    out.push("  );".to_owned());
    out.push("}".to_owned());
    out.push(String::new());
    out.push("function scalarPredicate(".to_owned());
    out.push("  path: string,".to_owned());
    out.push("  value: unknown,".to_owned());
    out.push("  filter: string,".to_owned());
    out.push("  ctx: WhereBuildCtx,".to_owned());
    out.push("): string[] {".to_owned());
    out.push("  if (value === undefined) return [];".to_owned());
    out.push("  if (!isScalarFilterObject(value)) {".to_owned());
    out.push("    return [`${path} = ${nextWhereVar(ctx, value)}`];".to_owned());
    out.push("  }".to_owned());
    out.push("  const parts: string[] = [];".to_owned());
    out.push("  if (value.equals !== undefined) parts.push(`${path} = ${nextWhereVar(ctx, value.equals)}`);".to_owned());
    out.push("  if (value.in !== undefined) parts.push(`${path} IN ${nextWhereVar(ctx, value.in)}`);".to_owned());
    out.push("  if (value.contains !== undefined) {".to_owned());
    out.push("    if (filter === \"array\") parts.push(`${path} CONTAINS ${nextWhereVar(ctx, value.contains)}`);".to_owned());
    out.push(
        "    else parts.push(`string::contains(${path}, ${nextWhereVar(ctx, value.contains)})`);"
            .to_owned(),
    );
    out.push("  }".to_owned());
    out.push("  if (value.gt !== undefined) parts.push(`${path} > ${nextWhereVar(ctx, value.gt)}`);".to_owned());
    out.push("  if (value.gte !== undefined) parts.push(`${path} >= ${nextWhereVar(ctx, value.gte)}`);".to_owned());
    out.push("  if (value.lt !== undefined) parts.push(`${path} < ${nextWhereVar(ctx, value.lt)}`);".to_owned());
    out.push("  if (value.lte !== undefined) parts.push(`${path} <= ${nextWhereVar(ctx, value.lte)}`);".to_owned());
    out.push("  return parts;".to_owned());
    out.push("}".to_owned());
    out.push(String::new());
    out.push("function relationMode(value: Record<string, unknown>, list: boolean): {".to_owned());
    out.push("  mode: \"some\" | \"every\" | \"none\" | \"is\";".to_owned());
    out.push("  nested: unknown;".to_owned());
    out.push("} {".to_owned());
    out.push("  if (\"some\" in value) return { mode: \"some\", nested: value.some };".to_owned());
    out.push("  if (\"every\" in value) return { mode: \"every\", nested: value.every };".to_owned());
    out.push("  if (\"none\" in value) return { mode: \"none\", nested: value.none };".to_owned());
    out.push("  if (\"is\" in value) return { mode: \"is\", nested: value.is };".to_owned());
    out.push("  return { mode: list ? \"some\" : \"is\", nested: value };".to_owned());
    out.push("}".to_owned());
    out.push(String::new());
    out.push("function listRelationPredicate(".to_owned());
    out.push("  collectionExpr: string,".to_owned());
    out.push("  mode: \"some\" | \"every\" | \"none\" | \"is\",".to_owned());
    out.push("  nestedClause: string,".to_owned());
    out.push("): string | null {".to_owned());
    out.push("  if (mode === \"is\") return null;".to_owned());
    out.push("  if (mode === \"some\") {".to_owned());
    out.push("    return nestedClause".to_owned());
    out.push("      ? `array::len(${collectionExpr}[WHERE ${nestedClause}]) > 0`".to_owned());
    out.push("      : `array::len(${collectionExpr}) > 0`;".to_owned());
    out.push("  }".to_owned());
    out.push("  if (mode === \"every\") {".to_owned());
    out.push("    return nestedClause".to_owned());
    out.push("      ? `array::len(${collectionExpr}[WHERE ${nestedClause}]) = array::len(${collectionExpr})`".to_owned());
    out.push("      : \"true\";".to_owned());
    out.push("  }".to_owned());
    out.push("  return nestedClause".to_owned());
    out.push("    ? `array::len(${collectionExpr}[WHERE ${nestedClause}]) = 0`".to_owned());
    out.push("    : `array::len(${collectionExpr}) = 0`;".to_owned());
    out.push("}".to_owned());
    out.push(String::new());
    out.push("function buildWhere(".to_owned());
    out.push("  where: Record<string, unknown> | undefined,".to_owned());
    out.push("  table: string,".to_owned());
    out.push("  allMeta: Record<string, Record<string, FieldSelectMeta>> = SelectMetaByTable,".to_owned());
    out.push("  ctx: WhereBuildCtx = { vars: {}, n: 0 },".to_owned());
    out.push("  pathPrefix = \"\",".to_owned());
    out.push("): string {".to_owned());
    out.push("  if (!where) return \"\";".to_owned());
    out.push("  const meta = allMeta[table] ?? {};".to_owned());
    out.push("  const parts: string[] = [];".to_owned());
    out.push("  for (const [key, value] of Object.entries(where)) {".to_owned());
    out.push("    if (value === undefined) continue;".to_owned());
    out.push("    if (key === \"AND\") {".to_owned());
    out.push("      const items = Array.isArray(value) ? value : [value];".to_owned());
    out.push("      const inner = items".to_owned());
    out.push("        .map((item) => buildWhere(item as Record<string, unknown>, table, allMeta, ctx, pathPrefix))".to_owned());
    out.push("        .filter(Boolean);".to_owned());
    out.push("      if (inner.length) parts.push(`(${inner.join(\" AND \")})`);".to_owned());
    out.push("      continue;".to_owned());
    out.push("    }".to_owned());
    out.push("    if (key === \"OR\") {".to_owned());
    out.push("      const items = Array.isArray(value) ? value : [value];".to_owned());
    out.push("      const inner = items".to_owned());
    out.push("        .map((item) => buildWhere(item as Record<string, unknown>, table, allMeta, ctx, pathPrefix))".to_owned());
    out.push("        .filter(Boolean);".to_owned());
    out.push("      if (inner.length) parts.push(`(${inner.join(\" OR \")})`);".to_owned());
    out.push("      continue;".to_owned());
    out.push("    }".to_owned());
    out.push("    if (key === \"NOT\") {".to_owned());
    out.push("      const items = Array.isArray(value) ? value : [value];".to_owned());
    out.push("      const inner = items".to_owned());
    out.push("        .map((item) => buildWhere(item as Record<string, unknown>, table, allMeta, ctx, pathPrefix))".to_owned());
    out.push("        .filter(Boolean);".to_owned());
    out.push("      if (inner.length === 1) parts.push(`!(${inner[0]})`);".to_owned());
    out.push("      else if (inner.length > 1) parts.push(`!((${inner.join(\" AND \")}))`);".to_owned());
    out.push("      continue;".to_owned());
    out.push("    }".to_owned());
    out.push("    const fieldMeta = meta[key];".to_owned());
    out.push("    if (!fieldMeta) continue;".to_owned());
    out.push("    const path = pathPrefix ? `${pathPrefix}.${key}` : key;".to_owned());
    out.push("    if (fieldMeta.kind === \"scalar\") {".to_owned());
    out.push("      parts.push(...scalarPredicate(path, value, fieldMeta.filter, ctx));".to_owned());
    out.push("      continue;".to_owned());
    out.push("    }".to_owned());
    out.push("    if (!value || typeof value !== \"object\" || Array.isArray(value)) continue;".to_owned());
    out.push("    const { mode, nested } = relationMode(value as Record<string, unknown>, fieldMeta.list);".to_owned());
    out.push("    if (fieldMeta.kind === \"edge\") {".to_owned());
    out.push("      const arrow = fieldMeta.dir === \"out\" ? `->${fieldMeta.edgeTable}` : `<-${fieldMeta.edgeTable}`;".to_owned());
    out.push("      const nestedClause = buildWhere(".to_owned());
    out.push("        nested as Record<string, unknown> | undefined,".to_owned());
    out.push("        fieldMeta.edgeTable,".to_owned());
    out.push("        allMeta,".to_owned());
    out.push("        ctx,".to_owned());
    out.push("      );".to_owned());
    out.push("      const pred = listRelationPredicate(arrow, mode, nestedClause);".to_owned());
    out.push("      if (pred) parts.push(pred);".to_owned());
    out.push("      continue;".to_owned());
    out.push("    }".to_owned());
    out.push("    if (fieldMeta.list) {".to_owned());
    out.push("      const nestedClause = buildWhere(".to_owned());
    out.push("        nested as Record<string, unknown> | undefined,".to_owned());
    out.push("        fieldMeta.targetTable,".to_owned());
    out.push("        allMeta,".to_owned());
    out.push("        ctx,".to_owned());
    out.push("      );".to_owned());
    out.push("      const pred = listRelationPredicate(path, mode, nestedClause);".to_owned());
    out.push("      if (pred) parts.push(pred);".to_owned());
    out.push("      continue;".to_owned());
    out.push("    }".to_owned());
    out.push("    const nestedClause = buildWhere(".to_owned());
    out.push("      nested as Record<string, unknown> | undefined,".to_owned());
    out.push("      fieldMeta.targetTable,".to_owned());
    out.push("      allMeta,".to_owned());
    out.push("      ctx,".to_owned());
    out.push("      path,".to_owned());
    out.push("    );".to_owned());
    out.push("    if (nestedClause) parts.push(nestedClause);".to_owned());
    out.push("  }".to_owned());
    out.push("  return parts.join(\" AND \");".to_owned());
    out.push("}".to_owned());
    out.push(String::new());
}

fn emit_select_helpers(out: &mut Vec<String>, schema: &DatabaseSchema, naming: &NamingContext<'_>) {
    for model in &schema.models {
        let table = model.table_name(naming.convention());
        let fetch_fields = fetch_field_names(model, naming);
        let fetch_lit = js_string_array(&fetch_fields);
        out.push(format!(
            "/** Fetch stored `{name}` row (links as RecordId). */",
            name = model.name
        ));
        out.push(format!(
            "export async function select{}(db: SurrealOpsLike, id: RecordId<\"{table}\"> | string): Promise<{} | undefined> {{",
            model.name, model.name
        ));
        out.push(format!(
            "  return selectRecord<{}>(db, \"{table}\", id);",
            model.name
        ));
        out.push("}".to_owned());
        out.push(String::new());

        out.push(format!(
            "/** Fetch `{name}` with related link/@relation fields expanded. */",
            name = model.name
        ));
        out.push(format!(
            "export async function select{}Related(db: SurrealOpsLike, id: RecordId<\"{table}\"> | string): Promise<{}Selected | undefined> {{",
            model.name, model.name
        ));
        out.push(format!(
            "  return selectRecordRelated<{}Selected>(db, \"{table}\", id, {fetch_lit});",
            model.name
        ));
        out.push("}".to_owned());
        out.push(String::new());
    }

    for edge in &schema.edges {
        let table = edge.table_name(naming.convention());
        out.push(format!("/** Fetch stored `{name}` edge row. */", name = edge.name));
        out.push(format!(
            "export async function select{}(db: SurrealOpsLike, id: RecordId<\"{table}\"> | string): Promise<{} | undefined> {{",
            edge.name, edge.name
        ));
        out.push(format!(
            "  return selectRecord<{}>(db, \"{table}\", id);",
            edge.name
        ));
        out.push("}".to_owned());
        out.push(String::new());

        out.push(format!(
            "/** Fetch `{name}` edge with `in`/`out` expanded. */",
            name = edge.name
        ));
        out.push(format!(
            "export async function select{}Related(db: SurrealOpsLike, id: RecordId<\"{table}\"> | string): Promise<{}Selected | undefined> {{",
            edge.name, edge.name
        ));
        out.push(format!(
            "  return selectRecordRelated<{}Selected>(db, \"{table}\", id, [\"in\", \"out\"]);",
            edge.name
        ));
        out.push("}".to_owned());
        out.push(String::new());
    }
}

fn emit_crud_helpers(out: &mut Vec<String>, schema: &DatabaseSchema, naming: &NamingContext<'_>) {
    for model in &schema.models {
        let table = model.table_name(naming.convention());
        out.push(format!(
            "export async function create{}(db: SurrealOpsLike, data: {}CreateInput): Promise<{}> {{",
            model.name, model.name, model.name
        ));
        out.push(format!(
            "  return createRecord<{}>(db, \"{table}\", data as Record<string, unknown>);",
            model.name
        ));
        out.push("}".to_owned());
        out.push(String::new());

        out.push(format!(
            "export async function update{}(db: SurrealOpsLike, id: RecordId<\"{table}\"> | string, data: {}UpdateInput): Promise<{} | undefined> {{",
            model.name, model.name, model.name
        ));
        out.push(format!(
            "  return updateRecord<{}>(db, \"{table}\", id, data as Record<string, unknown>);",
            model.name
        ));
        out.push("}".to_owned());
        out.push(String::new());

        out.push(format!(
            "export async function delete{}(db: SurrealOpsLike, id: RecordId<\"{table}\"> | string): Promise<void> {{",
            model.name
        ));
        out.push(format!("  return deleteRecord(db, \"{table}\", id);"));
        out.push("}".to_owned());
        out.push(String::new());
    }

    for edge in &schema.edges {
        let table = edge.table_name(naming.convention());
        let in_table = table_for_model_name(schema, &edge.in_model, naming);
        let out_table = table_for_model_name(schema, &edge.out_model, naming);
        out.push(format!(
            "export async function create{}(db: SurrealOpsLike, data: {}CreateInput): Promise<{}> {{",
            edge.name, edge.name, edge.name
        ));
        out.push(format!(
            "  const row = await db.query(`RELATE $in->{table}->$out CONTENT $content`, {{"
        ));
        out.push(format!("    in: normalizeThing(\"{in_table}\", String(data.in)),"));
        out.push(format!("    out: normalizeThing(\"{out_table}\", String(data.out)),"));
        out.push("    content: Object.fromEntries(".to_owned());
        out.push(
            "      Object.entries(data).filter(([key]) => key !== \"in\" && key !== \"out\"),"
                .to_owned(),
        );
        out.push("    ),".to_owned());
        out.push("  });".to_owned());
        out.push(format!(
            "  const created = await firstRow<{}>(row);",
            edge.name
        ));
        out.push(format!(
            "  if (!created) throw new Error(\"create{} returned no row\");",
            edge.name
        ));
        out.push("  return created;".to_owned());
        out.push("}".to_owned());
        out.push(String::new());

        out.push(format!(
            "export async function update{}(db: SurrealOpsLike, id: RecordId<\"{table}\"> | string, data: {}UpdateInput): Promise<{} | undefined> {{",
            edge.name, edge.name, edge.name
        ));
        out.push(format!(
            "  return updateRecord<{}>(db, \"{table}\", id, data as Record<string, unknown>);",
            edge.name
        ));
        out.push("}".to_owned());
        out.push(String::new());

        out.push(format!(
            "export async function delete{}(db: SurrealOpsLike, id: RecordId<\"{table}\"> | string): Promise<void> {{",
            edge.name
        ));
        out.push(format!("  return deleteRecord(db, \"{table}\", id);"));
        out.push("}".to_owned());
        out.push(String::new());
    }
}

fn emit_query_helpers(out: &mut Vec<String>, schema: &DatabaseSchema, _naming: &NamingContext<'_>) {
    for model in &schema.models {
        let fn_name = query_fn_name(&model.name);
        let related = query_related_fn_name(&model.name);
        out.push(format!(
            "export async function {fn_name}(db: SurrealOpsLike, sql: string, vars?: Record<string, unknown>): Promise<{}[]> {{",
            model.name
        ));
        out.push(format!("  return queryRows<{}>(db, sql, vars);", model.name));
        out.push("}".to_owned());
        out.push(String::new());

        out.push(format!(
            "export async function {related}(db: SurrealOpsLike, sql: string, vars?: Record<string, unknown>): Promise<{}Selected[]> {{",
            model.name
        ));
        out.push(format!(
            "  return queryRows<{}Selected>(db, sql, vars);",
            model.name
        ));
        out.push("}".to_owned());
        out.push(String::new());
    }

    for edge in &schema.edges {
        let fn_name = query_fn_name(&edge.name);
        let related = query_related_fn_name(&edge.name);
        out.push(format!(
            "export async function {fn_name}(db: SurrealOpsLike, sql: string, vars?: Record<string, unknown>): Promise<{}[]> {{",
            edge.name
        ));
        out.push(format!("  return queryRows<{}>(db, sql, vars);", edge.name));
        out.push("}".to_owned());
        out.push(String::new());

        out.push(format!(
            "export async function {related}(db: SurrealOpsLike, sql: string, vars?: Record<string, unknown>): Promise<{}Selected[]> {{",
            edge.name
        ));
        out.push(format!(
            "  return queryRows<{}Selected>(db, sql, vars);",
            edge.name
        ));
        out.push("}".to_owned());
        out.push(String::new());
    }
}

fn emit_fluent_client(out: &mut Vec<String>, schema: &DatabaseSchema, naming: &NamingContext<'_>) {
    out.push("async function runTransaction<T>(".to_owned());
    out.push("  db: SurrealLike,".to_owned());
    out.push("  fn: (tx: ReturnType<typeof buildClientDelegates>) => Promise<T>,".to_owned());
    out.push("): Promise<T> {".to_owned());
    out.push("  const txn = await db.beginTransaction();".to_owned());
    out.push("  const tx = buildClientDelegates(txn);".to_owned());
    out.push("  try {".to_owned());
    out.push("    const result = await fn(tx);".to_owned());
    out.push("    await txn.commit();".to_owned());
    out.push("    return result;".to_owned());
    out.push("  } catch (err) {".to_owned());
    out.push("    try {".to_owned());
    out.push("      await txn.cancel();".to_owned());
    out.push("    } catch {".to_owned());
    out.push("      // ignore cancel errors after a failed transaction".to_owned());
    out.push("    }".to_owned());
    out.push("    throw err;".to_owned());
    out.push("  }".to_owned());
    out.push("}".to_owned());
    out.push(String::new());

    out.push("function buildClientDelegates(db: SurrealOpsLike) {".to_owned());
    out.push("  return {".to_owned());

    for model in &schema.models {
        emit_fluent_model_delegate(out, model, naming);
    }
    for edge in &schema.edges {
        emit_fluent_edge_delegate(out, edge, naming);
    }

    out.push("  } as const;".to_owned());
    out.push("}".to_owned());
    out.push(String::new());

    out.push("export type TransactionClient = ReturnType<typeof buildClientDelegates>;".to_owned());
    out.push(String::new());
    out.push("export function createClient(db: SurrealLike) {".to_owned());
    out.push("  return {".to_owned());
    out.push("    ...buildClientDelegates(db),".to_owned());
    out.push("    $transaction: <T>(fn: (tx: TransactionClient) => Promise<T>): Promise<T> =>".to_owned());
    out.push("      runTransaction(db, fn),".to_owned());
    out.push("  } as const;".to_owned());
    out.push("}".to_owned());
    out.push(String::new());
}

fn emit_fluent_model_delegate(out: &mut Vec<String>, model: &Model, naming: &NamingContext<'_>) {
    let key = client_key(&model.name);
    let table = model.table_name(naming.convention());
    out.push(format!("    {key}: {{"));
    out.push(format!(
        "      findUnique: <S extends {}Select | undefined = undefined>(args: {{",
        model.name
    ));
    out.push(format!("        where: {}WhereInput;", model.name));
    out.push("        select?: S;".to_owned());
    out.push("        vars?: Record<string, unknown>;".to_owned());
    out.push(format!(
        "      }}): Promise<{}GetPayload<S> | undefined> =>",
        model.name
    ));
    out.push(format!(
        "        findUniqueRecord(db, \"{table}\", args as {{ where: Record<string, unknown>; select?: Record<string, unknown>; vars?: Record<string, unknown> }}) as Promise<{}GetPayload<S> | undefined>,",
        model.name
    ));
    out.push(format!(
        "      findMany: <S extends {}Select | undefined = undefined>(args: {{",
        model.name
    ));
    out.push("        select?: S;".to_owned());
    out.push(format!("        where?: {}WhereInput;", model.name));
    out.push(format!(
        "        orderBy?: {}OrderByInput | {}OrderByInput[];",
        model.name, model.name
    ));
    out.push("        take?: number;".to_owned());
    out.push("        skip?: number;".to_owned());
    out.push("        whereSql?: string;".to_owned());
    out.push("        vars?: Record<string, unknown>;".to_owned());
    out.push(format!(
        "      }} = {{}}): Promise<{}GetPayload<S>[]> =>",
        model.name
    ));
    out.push(format!(
        "        findManyRecords(db, \"{table}\", args as {{ select?: Record<string, unknown>; where?: Record<string, unknown>; orderBy?: Record<string, unknown> | Record<string, unknown>[]; take?: number; skip?: number; whereSql?: string; vars?: Record<string, unknown> }}) as Promise<{}GetPayload<S>[]>,",
        model.name
    ));
    out.push(format!(
        "      create: (data: {}CreateInput): Promise<{}> => create{}(db, data),",
        model.name, model.name, model.name
    ));
    out.push(format!(
        "      createMany: <S extends {}Select | undefined = undefined>(args: {{",
        model.name
    ));
    out.push(format!("        data: {}CreateInput[];", model.name));
    out.push("        select?: S;".to_owned());
    out.push(format!(
        "      }}): Promise<S extends undefined ? {{ count: number }} : {}GetPayload<S>[]> =>",
        model.name
    ));
    out.push(format!(
        "        createManyVia(db, \"{table}\", args as {{ data: Record<string, unknown>[]; select?: Record<string, unknown> }}, (data) => create{}(db, data as {}CreateInput)) as Promise<S extends undefined ? {{ count: number }} : {}GetPayload<S>[]>,",
        model.name, model.name, model.name
    ));
    out.push(format!(
        "      update: (id: RecordId<\"{table}\"> | string, data: {}UpdateInput): Promise<{} | undefined> => update{}(db, id, data),",
        model.name, model.name, model.name
    ));
    out.push(format!(
        "      updateMany: <S extends {}Select | undefined = undefined>(args: {{",
        model.name
    ));
    out.push(format!("        where: {}WhereInput;", model.name));
    out.push(format!("        data: {}UpdateInput;", model.name));
    out.push("        select?: S;".to_owned());
    out.push(format!(
        "      }}): Promise<S extends undefined ? {{ count: number }} : {}GetPayload<S>[]> =>",
        model.name
    ));
    out.push(format!(
        "        updateManyRecords(db, \"{table}\", args as {{ where: Record<string, unknown>; data: Record<string, unknown>; select?: Record<string, unknown> }}) as Promise<S extends undefined ? {{ count: number }} : {}GetPayload<S>[]>,",
        model.name
    ));
    out.push(format!(
        "      delete: (id: RecordId<\"{table}\"> | string): Promise<void> => delete{}(db, id),",
        model.name
    ));
    out.push(format!(
        "      deleteMany: <S extends {}Select | undefined = undefined>(args: {{",
        model.name
    ));
    out.push(format!("        where: {}WhereInput;", model.name));
    out.push("        select?: S;".to_owned());
    out.push(format!(
        "      }}): Promise<S extends undefined ? {{ count: number }} : {}GetPayload<S>[]> =>",
        model.name
    ));
    out.push(format!(
        "        deleteManyRecords(db, \"{table}\", args as {{ where: Record<string, unknown>; select?: Record<string, unknown> }}) as Promise<S extends undefined ? {{ count: number }} : {}GetPayload<S>[]>,",
        model.name
    ));
    out.push(format!(
        "      upsert: <S extends {}Select | undefined = undefined>(args: {{",
        model.name
    ));
    out.push(format!("        where: {}WhereUniqueInput;", model.name));
    out.push(format!("        create: {}CreateInput;", model.name));
    out.push(format!("        update: {}UpdateInput;", model.name));
    out.push("        select?: S;".to_owned());
    out.push(format!(
        "      }}): Promise<{}GetPayload<S>> =>",
        model.name
    ));
    out.push(format!(
        "        upsertRecord(db, \"{table}\", args as {{ where: Record<string, unknown>; create: Record<string, unknown>; update: Record<string, unknown>; select?: Record<string, unknown> }}, (data) => create{}(db, data as {}CreateInput)) as Promise<{}GetPayload<S>>,",
        model.name, model.name, model.name
    ));
    out.push("    },".to_owned());
}

fn emit_fluent_edge_delegate(out: &mut Vec<String>, edge: &Edge, naming: &NamingContext<'_>) {
    let key = client_key(&edge.name);
    let table = edge.table_name(naming.convention());
    out.push(format!("    {key}: {{"));
    out.push(format!(
        "      findUnique: <S extends {}Select | undefined = undefined>(args: {{",
        edge.name
    ));
    out.push(format!("        where: {}WhereInput;", edge.name));
    out.push("        select?: S;".to_owned());
    out.push("        vars?: Record<string, unknown>;".to_owned());
    out.push(format!(
        "      }}): Promise<{}GetPayload<S> | undefined> =>",
        edge.name
    ));
    out.push(format!(
        "        findUniqueRecord(db, \"{table}\", args as {{ where: Record<string, unknown>; select?: Record<string, unknown>; vars?: Record<string, unknown> }}) as Promise<{}GetPayload<S> | undefined>,",
        edge.name
    ));
    out.push(format!(
        "      create: (data: {}CreateInput): Promise<{}> => create{}(db, data),",
        edge.name, edge.name, edge.name
    ));
    out.push(format!(
        "      createMany: <S extends {}Select | undefined = undefined>(args: {{",
        edge.name
    ));
    out.push(format!("        data: {}CreateInput[];", edge.name));
    out.push("        select?: S;".to_owned());
    out.push(format!(
        "      }}): Promise<S extends undefined ? {{ count: number }} : {}GetPayload<S>[]> =>",
        edge.name
    ));
    out.push(format!(
        "        createManyVia(db, \"{table}\", args as {{ data: Record<string, unknown>[]; select?: Record<string, unknown> }}, (data) => create{}(db, data as {}CreateInput)) as Promise<S extends undefined ? {{ count: number }} : {}GetPayload<S>[]>,",
        edge.name, edge.name, edge.name
    ));
    out.push(format!(
        "      update: (id: RecordId<\"{table}\"> | string, data: {}UpdateInput): Promise<{} | undefined> => update{}(db, id, data),",
        edge.name, edge.name, edge.name
    ));
    out.push(format!(
        "      updateMany: <S extends {}Select | undefined = undefined>(args: {{",
        edge.name
    ));
    out.push(format!("        where: {}WhereInput;", edge.name));
    out.push(format!("        data: {}UpdateInput;", edge.name));
    out.push("        select?: S;".to_owned());
    out.push(format!(
        "      }}): Promise<S extends undefined ? {{ count: number }} : {}GetPayload<S>[]> =>",
        edge.name
    ));
    out.push(format!(
        "        updateManyRecords(db, \"{table}\", args as {{ where: Record<string, unknown>; data: Record<string, unknown>; select?: Record<string, unknown> }}) as Promise<S extends undefined ? {{ count: number }} : {}GetPayload<S>[]>,",
        edge.name
    ));
    out.push(format!(
        "      delete: (id: RecordId<\"{table}\"> | string): Promise<void> => delete{}(db, id),",
        edge.name
    ));
    out.push(format!(
        "      deleteMany: <S extends {}Select | undefined = undefined>(args: {{",
        edge.name
    ));
    out.push(format!("        where: {}WhereInput;", edge.name));
    out.push("        select?: S;".to_owned());
    out.push(format!(
        "      }}): Promise<S extends undefined ? {{ count: number }} : {}GetPayload<S>[]> =>",
        edge.name
    ));
    out.push(format!(
        "        deleteManyRecords(db, \"{table}\", args as {{ where: Record<string, unknown>; select?: Record<string, unknown> }}) as Promise<S extends undefined ? {{ count: number }} : {}GetPayload<S>[]>,",
        edge.name
    ));
    out.push(format!(
        "      upsert: <S extends {}Select | undefined = undefined>(args: {{",
        edge.name
    ));
    out.push(format!("        where: {}WhereUniqueInput;", edge.name));
    out.push(format!("        create: {}CreateInput;", edge.name));
    out.push(format!("        update: {}UpdateInput;", edge.name));
    out.push("        select?: S;".to_owned());
    out.push(format!(
        "      }}): Promise<{}GetPayload<S>> =>",
        edge.name
    ));
    out.push(format!(
        "        upsertRecord(db, \"{table}\", args as {{ where: Record<string, unknown>; create: Record<string, unknown>; update: Record<string, unknown>; select?: Record<string, unknown> }}, (data) => create{}(db, data as {}CreateInput)) as Promise<{}GetPayload<S>>,",
        edge.name, edge.name, edge.name
    ));
    out.push("    },".to_owned());
}

fn js_string_array(items: &[String]) -> String {
    if items.is_empty() {
        "[]".to_owned()
    } else {
        format!(
            "[{}]",
            items
                .iter()
                .map(|item| format!("\"{item}\""))
                .collect::<Vec<_>>()
                .join(", ")
        )
    }
}

fn fetch_field_names(model: &Model, naming: &NamingContext<'_>) -> Vec<String> {
    model
        .fields
        .iter()
        .filter(|field| !field.name.contains('.'))
        .filter(|field| field.is_link() || field.relation_name.is_some())
        .map(|field| naming.field_name(field))
        .collect()
}
