#![allow(clippy::missing_errors_doc, clippy::too_many_lines)]

use super::TypeScriptProvider;
use super::types::table_for_model_name;
use core::{DatabaseSchema, DomainError, Edge, Model, NamingContext};

pub struct SurrealTypeScriptProvider;

impl TypeScriptProvider for SurrealTypeScriptProvider {
    fn id(&self) -> &'static str {
        "surrealdb"
    }

    fn emit(&self, schema: &DatabaseSchema) -> Result<String, DomainError> {
        Ok(emit_typescript(schema))
    }
}

fn emit_typescript(schema: &DatabaseSchema) -> String {
    let naming = NamingContext::new(&schema.naming, &schema.models);
    let mut out = vec![
        "// Generated by Awesome Schema".to_owned(),
        "// Requires the `awesome-schema` package and a SurrealDB JS client compatible with SurrealLike."
            .to_owned(),
        "import {".to_owned(),
        "  bindSchemaMeta,".to_owned(),
        "  selectRecord,".to_owned(),
        "  selectRecordRelated,".to_owned(),
        "  createWithNested,".to_owned(),
        "  updateWithNested,".to_owned(),
        "  updateOneRecord,".to_owned(),
        "  deleteRecord,".to_owned(),
        "  deleteOneRecord,".to_owned(),
        "  relateEdge,".to_owned(),
        "  updateRecord,".to_owned(),
        "  queryRows,".to_owned(),
        "  findUniqueRecord,".to_owned(),
        "  findManyRecords,".to_owned(),
        "  countRecords,".to_owned(),
        "  groupByRecords,".to_owned(),
        "  createManyVia,".to_owned(),
        "  updateManyRecords,".to_owned(),
        "  deleteManyRecords,".to_owned(),
        "  upsertRecord,".to_owned(),
        "  type RecordId,".to_owned(),
        "  type SurrealOpsLike,".to_owned(),
        "  type SurrealLike,".to_owned(),
        "  type SurrealTransactionLike,".to_owned(),
        "  type LiveAction,".to_owned(),
        "  type LiveHandle,".to_owned(),
        "  type MutationReturn,".to_owned(),
        "  type ManyReturnResult,".to_owned(),
        "  type SingleUpdateResult,".to_owned(),
        "  type SingleDeleteResult,".to_owned(),
        "  type SingleUpsertResult,".to_owned(),
        "} from \"awesome-schema/runtime\";".to_owned(),
        "export {".to_owned(),
        "  recordId,".to_owned(),
        "  parseRecordId,".to_owned(),
        "  asRecordId,".to_owned(),
        "  type RecordId,".to_owned(),
        "  type SurrealOpsLike,".to_owned(),
        "  type SurrealTransactionLike,".to_owned(),
        "  type SurrealLike,".to_owned(),
        "  type LiveAction,".to_owned(),
        "  type LiveHandle,".to_owned(),
        "  type MutationReturn,".to_owned(),
        "  type ManyReturnResult,".to_owned(),
        "  type SingleUpdateResult,".to_owned(),
        "  type SingleDeleteResult,".to_owned(),
        "  type SingleUpsertResult,".to_owned(),
        "} from \"awesome-schema/runtime\";".to_owned(),
        String::new(),
    ];

    super::types::emit_schema_types(&mut out, schema, &naming);
    out.push("bindSchemaMeta(SelectMetaByTable, WriteMetaByTable);".to_owned());
    out.push(String::new());
    emit_select_helpers(&mut out, schema, &naming);
    emit_crud_helpers(&mut out, schema, &naming);
    emit_query_helpers(&mut out, schema, &naming);
    emit_fluent_client(&mut out, schema, &naming);

    out.join("\n")
}

fn emit_select_helpers(out: &mut Vec<String>, schema: &DatabaseSchema, naming: &NamingContext<'_>) {
    for model in &schema.models {
        let table = model.table_name(naming.convention());
        let fetch_fields = fetch_field_names(model, naming);
        let fetch_lit = js_string_array(&fetch_fields);
        out.push(format!(
            "/** Fetch stored `{name}` row (links as RecordId). */",
            name = model.name
        ));
        out.push(format!(
            "export async function select{}(db: SurrealOpsLike, id: RecordId<\"{table}\"> | string): Promise<{} | undefined> {{",
            model.name, model.name
        ));
        out.push(format!("  return selectRecord<{}>(db, \"{table}\", id);", model.name));
        out.push("}".to_owned());
        out.push(String::new());

        out.push(format!(
            "/** Fetch `{name}` with related link/@relation fields expanded. */",
            name = model.name
        ));
        out.push(format!(
            "export async function select{}Related(db: SurrealOpsLike, id: RecordId<\"{table}\"> | string): Promise<{}Selected | undefined> {{",
            model.name, model.name
        ));
        out.push(format!(
            "  return selectRecordRelated<{}Selected>(db, \"{table}\", id, {fetch_lit});",
            model.name
        ));
        out.push("}".to_owned());
        out.push(String::new());
    }

    for edge in &schema.edges {
        let table = edge.table_name(naming.convention());
        out.push(format!("/** Fetch stored `{name}` edge row. */", name = edge.name));
        out.push(format!(
            "export async function select{}(db: SurrealOpsLike, id: RecordId<\"{table}\"> | string): Promise<{} | undefined> {{",
            edge.name, edge.name
        ));
        out.push(format!("  return selectRecord<{}>(db, \"{table}\", id);", edge.name));
        out.push("}".to_owned());
        out.push(String::new());

        out.push(format!("/** Fetch `{name}` edge with `in`/`out` expanded. */", name = edge.name));
        out.push(format!(
            "export async function select{}Related(db: SurrealOpsLike, id: RecordId<\"{table}\"> | string): Promise<{}Selected | undefined> {{",
            edge.name, edge.name
        ));
        out.push(format!(
            "  return selectRecordRelated<{}Selected>(db, \"{table}\", id, [\"in\", \"out\"]);",
            edge.name
        ));
        out.push("}".to_owned());
        out.push(String::new());
    }
}

fn emit_crud_helpers(out: &mut Vec<String>, schema: &DatabaseSchema, naming: &NamingContext<'_>) {
    for model in &schema.models {
        let table = model.table_name(naming.convention());
        out.push(format!(
            "export async function create{}(db: SurrealOpsLike, data: {}CreateInput): Promise<{}> {{",
            model.name, model.name, model.name
        ));
        out.push(format!(
            "  return createWithNested<{}>(db, \"{table}\", data as Record<string, unknown>);",
            model.name
        ));
        out.push("}".to_owned());
        out.push(String::new());

        out.push(format!(
            "export async function update{}(db: SurrealOpsLike, id: RecordId<\"{table}\"> | string, data: {}UpdateInput): Promise<{} | undefined> {{",
            model.name, model.name, model.name
        ));
        out.push(format!(
            "  return updateWithNested<{}>(db, \"{table}\", String(id), data as Record<string, unknown>) as Promise<{} | undefined>;",
            model.name, model.name
        ));
        out.push("}".to_owned());
        out.push(String::new());

        out.push(format!(
            "export async function delete{}(db: SurrealOpsLike, id: RecordId<\"{table}\"> | string): Promise<void> {{",
            model.name
        ));
        out.push(format!("  return deleteRecord(db, \"{table}\", id);"));
        out.push("}".to_owned());
        out.push(String::new());
    }

    for edge in &schema.edges {
        let table = edge.table_name(naming.convention());
        let in_table = table_for_model_name(schema, &edge.in_model, naming);
        let out_table = table_for_model_name(schema, &edge.out_model, naming);
        out.push(format!(
            "export async function create{}(db: SurrealOpsLike, data: {}CreateInput): Promise<{}> {{",
            edge.name, edge.name, edge.name
        ));
        out.push("  const content = Object.fromEntries(".to_owned());
        out.push(
            "    Object.entries(data).filter(([key]) => key !== \"in\" && key !== \"out\"),"
                .to_owned(),
        );
        out.push("  );".to_owned());
        out.push(format!(
            "  return relateEdge(db, \"{table}\", \"{in_table}\", \"{out_table}\", String(data.in), String(data.out), content) as Promise<{}>;",
            edge.name
        ));
        out.push("}".to_owned());
        out.push(String::new());

        out.push(format!(
            "export async function update{}(db: SurrealOpsLike, id: RecordId<\"{table}\"> | string, data: {}UpdateInput): Promise<{} | undefined> {{",
            edge.name, edge.name, edge.name
        ));
        out.push(format!(
            "  return updateRecord<{}>(db, \"{table}\", id, data as Record<string, unknown>);",
            edge.name
        ));
        out.push("}".to_owned());
        out.push(String::new());

        out.push(format!(
            "export async function delete{}(db: SurrealOpsLike, id: RecordId<\"{table}\"> | string): Promise<void> {{",
            edge.name
        ));
        out.push(format!("  return deleteRecord(db, \"{table}\", id);"));
        out.push("}".to_owned());
        out.push(String::new());
    }
}

fn emit_query_helpers(out: &mut Vec<String>, schema: &DatabaseSchema, _naming: &NamingContext<'_>) {
    for model in &schema.models {
        let fn_name = query_fn_name(&model.name);
        let related = query_related_fn_name(&model.name);
        out.push(format!(
            "export async function {fn_name}(db: SurrealOpsLike, sql: string, vars?: Record<string, unknown>): Promise<{}[]> {{",
            model.name
        ));
        out.push(format!("  return queryRows<{}>(db, sql, vars);", model.name));
        out.push("}".to_owned());
        out.push(String::new());

        out.push(format!(
            "export async function {related}(db: SurrealOpsLike, sql: string, vars?: Record<string, unknown>): Promise<{}Selected[]> {{",
            model.name
        ));
        out.push(format!("  return queryRows<{}Selected>(db, sql, vars);", model.name));
        out.push("}".to_owned());
        out.push(String::new());
    }

    for edge in &schema.edges {
        let fn_name = query_fn_name(&edge.name);
        let related = query_related_fn_name(&edge.name);
        out.push(format!(
            "export async function {fn_name}(db: SurrealOpsLike, sql: string, vars?: Record<string, unknown>): Promise<{}[]> {{",
            edge.name
        ));
        out.push(format!("  return queryRows<{}>(db, sql, vars);", edge.name));
        out.push("}".to_owned());
        out.push(String::new());

        out.push(format!(
            "export async function {related}(db: SurrealOpsLike, sql: string, vars?: Record<string, unknown>): Promise<{}Selected[]> {{",
            edge.name
        ));
        out.push(format!("  return queryRows<{}Selected>(db, sql, vars);", edge.name));
        out.push("}".to_owned());
        out.push(String::new());
    }
}

fn emit_fluent_client(out: &mut Vec<String>, schema: &DatabaseSchema, naming: &NamingContext<'_>) {
    out.push("async function runTransaction<T>(".to_owned());
    out.push("  db: SurrealLike,".to_owned());
    out.push("  fn: (tx: ReturnType<typeof buildClientDelegates>) => Promise<T>,".to_owned());
    out.push("): Promise<T> {".to_owned());
    out.push("  const txn = await db.beginTransaction();".to_owned());
    out.push("  const tx = buildClientDelegates(txn);".to_owned());
    out.push("  try {".to_owned());
    out.push("    const result = await fn(tx);".to_owned());
    out.push("    await txn.commit();".to_owned());
    out.push("    return result;".to_owned());
    out.push("  } catch (err) {".to_owned());
    out.push("    try {".to_owned());
    out.push("      await txn.cancel();".to_owned());
    out.push("    } catch {".to_owned());
    out.push("      // ignore cancel errors after a failed transaction".to_owned());
    out.push("    }".to_owned());
    out.push("    throw err;".to_owned());
    out.push("  }".to_owned());
    out.push("}".to_owned());
    out.push(String::new());

    out.push("async function openLiveSelect<T>(".to_owned());
    out.push("  db: SurrealLike,".to_owned());
    out.push("  sql: string,".to_owned());
    out.push("  vars?: Record<string, unknown>,".to_owned());
    out.push("): Promise<LiveHandle<T>> {".to_owned());
    out.push("  const trimmed = sql.trim();".to_owned());
    out.push("  if (!/^LIVE\\s+SELECT\\b/i.test(trimmed)) {".to_owned());
    out.push("    throw new Error(\"$live: sql must be a LIVE SELECT statement\");".to_owned());
    out.push("  }".to_owned());
    out.push("  const result = await db.query(trimmed, vars);".to_owned());
    out.push("  const id = Array.isArray(result) ? result[0] : result;".to_owned());
    out.push("  return db.liveOf<T>(id);".to_owned());
    out.push("}".to_owned());
    out.push(String::new());

    out.push("function buildClientDelegates(db: SurrealOpsLike) {".to_owned());
    out.push("  return {".to_owned());

    for model in &schema.models {
        emit_fluent_model_delegate(out, model, naming);
    }
    for edge in &schema.edges {
        emit_fluent_edge_delegate(out, edge, naming);
    }

    out.push(
        "    $queryRaw: <T = unknown>(sql: string, vars?: Record<string, unknown>): Promise<T[]> =>"
            .to_owned(),
    );
    out.push("      queryRows<T>(db, sql, vars),".to_owned());
    out.push(
        "    $executeRaw: (sql: string, vars?: Record<string, unknown>): Promise<unknown> =>"
            .to_owned(),
    );
    out.push("      db.query(sql, vars),".to_owned());

    out.push("  } as const;".to_owned());
    out.push("}".to_owned());
    out.push(String::new());

    out.push("export type TransactionClient = ReturnType<typeof buildClientDelegates>;".to_owned());
    out.push(String::new());
    out.push("export function createClient(db: SurrealLike) {".to_owned());
    out.push("  const base = buildClientDelegates(db);".to_owned());
    out.push("  return {".to_owned());
    out.push("    ...base,".to_owned());
    for model in &schema.models {
        let table = model.table_name(naming.convention());
        emit_session_live(out, &model.name, &table);
    }
    for edge in &schema.edges {
        let table = edge.table_name(naming.convention());
        emit_session_live(out, &edge.name, &table);
    }
    out.push(
        "    $transaction: <T>(fn: (tx: TransactionClient) => Promise<T>): Promise<T> =>"
            .to_owned(),
    );
    out.push("      runTransaction(db, fn),".to_owned());
    out.push(
        "    $live: <T = unknown>(sql: string, vars?: Record<string, unknown>): Promise<LiveHandle<T>> =>"
            .to_owned(),
    );
    out.push("      openLiveSelect<T>(db, sql, vars),".to_owned());
    out.push("  } as const;".to_owned());
    out.push("}".to_owned());
    out.push(String::new());
}

fn emit_session_live(out: &mut Vec<String>, name: &str, table: &str) {
    let key = client_key(name);
    out.push(format!("    {key}: {{"));
    out.push(format!("      ...base.{key},"));
    out.push(format!(
        "      live: (): Promise<LiveHandle<{name}>> => db.live<{name}>(\"{table}\"),"
    ));
    out.push("    },".to_owned());
}

fn emit_fluent_model_delegate(out: &mut Vec<String>, model: &Model, naming: &NamingContext<'_>) {
    let key = client_key(&model.name);
    let table = model.table_name(naming.convention());
    out.push(format!("    {key}: {{"));
    out.push(format!(
        "      findUnique: <S extends {}Select | undefined = undefined>(args: {{",
        model.name
    ));
    out.push(format!("        where: {}WhereInput;", model.name));
    out.push("        select?: S;".to_owned());
    out.push("        vars?: Record<string, unknown>;".to_owned());
    out.push(format!("      }}): Promise<{}GetPayload<S> | undefined> =>", model.name));
    out.push(format!(
        "        findUniqueRecord(db, \"{table}\", args as {{ where: Record<string, unknown>; select?: Record<string, unknown>; vars?: Record<string, unknown> }}) as Promise<{}GetPayload<S> | undefined>,",
        model.name
    ));
    out.push(format!(
        "      findMany: <S extends {}Select | undefined = undefined>(args: {{",
        model.name
    ));
    out.push("        select?: S;".to_owned());
    out.push(format!("        where?: {}WhereInput;", model.name));
    out.push(format!(
        "        orderBy?: {}OrderByInput | {}OrderByInput[];",
        model.name, model.name
    ));
    out.push("        take?: number;".to_owned());
    out.push("        skip?: number;".to_owned());
    out.push("        whereSql?: string;".to_owned());
    out.push("        vars?: Record<string, unknown>;".to_owned());
    out.push(format!("      }} = {{}}): Promise<{}GetPayload<S>[]> =>", model.name));
    out.push(format!(
        "        findManyRecords(db, \"{table}\", args as {{ select?: Record<string, unknown>; where?: Record<string, unknown>; orderBy?: Record<string, unknown> | Record<string, unknown>[]; take?: number; skip?: number; whereSql?: string; vars?: Record<string, unknown> }}) as Promise<{}GetPayload<S>[]>,",
        model.name
    ));
    out.push(format!(
        "      count: (args: {{ where?: {}WhereInput }} = {{}}): Promise<number> =>",
        model.name
    ));
    out.push(format!(
        "        countRecords(db, \"{table}\", args as {{ where?: Record<string, unknown> }}),"
    ));
    out.push("      groupBy: (args: {".to_owned());
    out.push(format!("        by: {}ScalarFieldEnum[];", model.name));
    out.push(format!("        where?: {}WhereInput;", model.name));
    out.push(format!(
        "        _count?: true | {{ _all?: true }} & Partial<Record<{}ScalarFieldEnum, true>>;",
        model.name
    ));
    out.push(format!("        _sum?: Partial<Record<{}NumericFieldEnum, true>>;", model.name));
    out.push(format!("        _avg?: Partial<Record<{}NumericFieldEnum, true>>;", model.name));
    out.push(format!("        _min?: Partial<Record<{}NumericFieldEnum, true>>;", model.name));
    out.push(format!("        _max?: Partial<Record<{}NumericFieldEnum, true>>;", model.name));
    out.push(format!("        having?: {}HavingInput;", model.name));
    out.push(format!(
        "        orderBy?: {}GroupByOrderByInput | {}GroupByOrderByInput[];",
        model.name, model.name
    ));
    out.push("        take?: number;".to_owned());
    out.push("        skip?: number;".to_owned());
    out.push("      }): Promise<Record<string, unknown>[]> =>".to_owned());
    out.push(format!(
        "        groupByRecords(db, \"{table}\", args as {{ by: string[]; where?: Record<string, unknown>; _count?: true | Record<string, boolean | undefined>; _sum?: Record<string, boolean | undefined>; _avg?: Record<string, boolean | undefined>; _min?: Record<string, boolean | undefined>; _max?: Record<string, boolean | undefined>; having?: Record<string, unknown>; orderBy?: Record<string, unknown> | Record<string, unknown>[]; take?: number; skip?: number }}),"
    ));
    out.push(format!(
        "      create: (data: {}CreateInput): Promise<{}> => create{}(db, data),",
        model.name, model.name, model.name
    ));
    out.push(format!(
        "      createMany: <S extends {}Select | undefined = undefined, R extends Exclude<MutationReturn, \"BEFORE\"> | undefined = undefined>(args: {{",
        model.name
    ));
    out.push(format!("        data: {}CreateInput[];", model.name));
    out.push("        select?: S;".to_owned());
    out.push("        return?: R;".to_owned());
    out.push(format!(
        "      }}): Promise<ManyReturnResult<S, R, {}, {}GetPayload<S>>> =>",
        model.name, model.name
    ));
    out.push(format!(
        "        createManyVia(db, \"{table}\", args as {{ data: Record<string, unknown>[]; select?: Record<string, unknown>; return?: MutationReturn }}, (data) => create{}(db, data as {}CreateInput), false) as Promise<ManyReturnResult<S, R, {}, {}GetPayload<S>>>,",
        model.name, model.name, model.name, model.name
    ));
    out.push(format!(
        "      update: <S extends {}Select | undefined = undefined, R extends MutationReturn | undefined = undefined>(",
        model.name
    ));
    out.push(format!(
        "        id: RecordId<\"{table}\"> | string, data: {}UpdateInput, opts?: {{ select?: S; return?: R }},",
        model.name
    ));
    out.push(format!(
        "      ): Promise<SingleUpdateResult<S, R, {}, {}GetPayload<S>>> =>",
        model.name, model.name
    ));
    out.push(format!(
        "        updateWithNested(db, \"{table}\", String(id), data as Record<string, unknown>, opts as {{ select?: Record<string, unknown>; return?: MutationReturn }} | undefined) as Promise<SingleUpdateResult<S, R, {}, {}GetPayload<S>>>,",
        model.name, model.name
    ));
    out.push(format!(
        "      updateMany: <S extends {}Select | undefined = undefined, R extends MutationReturn | undefined = undefined>(args: {{",
        model.name
    ));
    out.push(format!("        where: {}WhereInput;", model.name));
    out.push(format!("        data: {}UpdateInput;", model.name));
    out.push("        select?: S;".to_owned());
    out.push("        return?: R;".to_owned());
    out.push(format!(
        "      }}): Promise<ManyReturnResult<S, R, {}, {}GetPayload<S>>> =>",
        model.name, model.name
    ));
    out.push(format!(
        "        updateManyRecords(db, \"{table}\", args as {{ where: Record<string, unknown>; data: Record<string, unknown>; select?: Record<string, unknown>; return?: MutationReturn }}) as Promise<ManyReturnResult<S, R, {}, {}GetPayload<S>>>,",
        model.name, model.name
    ));
    out.push(format!(
        "      delete: <S extends {}Select | undefined = undefined, R extends Exclude<MutationReturn, \"AFTER\"> | undefined = undefined>(",
        model.name
    ));
    out.push(format!(
        "        id: RecordId<\"{table}\"> | string, opts?: {{ select?: S; return?: R }},"
    ));
    out.push(format!(
        "      ): Promise<SingleDeleteResult<S, R, {}, {}GetPayload<S>>> =>",
        model.name, model.name
    ));
    out.push(format!(
        "        deleteOneRecord(db, \"{table}\", String(id), opts as {{ select?: Record<string, unknown>; return?: MutationReturn }} | undefined) as Promise<SingleDeleteResult<S, R, {}, {}GetPayload<S>>>,",
        model.name, model.name
    ));
    out.push(format!(
        "      deleteMany: <S extends {}Select | undefined = undefined, R extends Exclude<MutationReturn, \"AFTER\"> | undefined = undefined>(args: {{",
        model.name
    ));
    out.push(format!("        where: {}WhereInput;", model.name));
    out.push("        select?: S;".to_owned());
    out.push("        return?: R;".to_owned());
    out.push(format!(
        "      }}): Promise<ManyReturnResult<S, R, {}, {}GetPayload<S>>> =>",
        model.name, model.name
    ));
    out.push(format!(
        "        deleteManyRecords(db, \"{table}\", args as {{ where: Record<string, unknown>; select?: Record<string, unknown>; return?: MutationReturn }}) as Promise<ManyReturnResult<S, R, {}, {}GetPayload<S>>>,",
        model.name, model.name
    ));
    out.push(format!(
        "      upsert: <S extends {}Select | undefined = undefined, R extends MutationReturn | undefined = undefined>(args: {{",
        model.name
    ));
    out.push(format!("        where: {}WhereUniqueInput;", model.name));
    out.push(format!("        create: {}CreateInput;", model.name));
    out.push(format!("        update: {}UpdateInput;", model.name));
    out.push("        select?: S;".to_owned());
    out.push("        return?: R;".to_owned());
    out.push(format!(
        "      }}): Promise<SingleUpsertResult<S, R, {}, {}GetPayload<S>>> =>",
        model.name, model.name
    ));
    out.push(format!(
        "        upsertRecord(db, \"{table}\", args as {{ where: Record<string, unknown>; create: Record<string, unknown>; update: Record<string, unknown>; select?: Record<string, unknown>; return?: MutationReturn }}, (data) => create{}(db, data as {}CreateInput)) as Promise<SingleUpsertResult<S, R, {}, {}GetPayload<S>>>,",
        model.name, model.name, model.name, model.name
    ));
    out.push("    },".to_owned());
}

fn emit_fluent_edge_delegate(out: &mut Vec<String>, edge: &Edge, naming: &NamingContext<'_>) {
    let key = client_key(&edge.name);
    let table = edge.table_name(naming.convention());
    out.push(format!("    {key}: {{"));
    out.push(format!(
        "      findUnique: <S extends {}Select | undefined = undefined>(args: {{",
        edge.name
    ));
    out.push(format!("        where: {}WhereInput;", edge.name));
    out.push("        select?: S;".to_owned());
    out.push("        vars?: Record<string, unknown>;".to_owned());
    out.push(format!("      }}): Promise<{}GetPayload<S> | undefined> =>", edge.name));
    out.push(format!(
        "        findUniqueRecord(db, \"{table}\", args as {{ where: Record<string, unknown>; select?: Record<string, unknown>; vars?: Record<string, unknown> }}) as Promise<{}GetPayload<S> | undefined>,",
        edge.name
    ));
    out.push(format!(
        "      count: (args: {{ where?: {}WhereInput }} = {{}}): Promise<number> =>",
        edge.name
    ));
    out.push(format!(
        "        countRecords(db, \"{table}\", args as {{ where?: Record<string, unknown> }}),"
    ));
    out.push("      groupBy: (args: {".to_owned());
    out.push(format!("        by: {}ScalarFieldEnum[];", edge.name));
    out.push(format!("        where?: {}WhereInput;", edge.name));
    out.push(format!(
        "        _count?: true | {{ _all?: true }} & Partial<Record<{}ScalarFieldEnum, true>>;",
        edge.name
    ));
    out.push(format!("        _sum?: Partial<Record<{}NumericFieldEnum, true>>;", edge.name));
    out.push(format!("        _avg?: Partial<Record<{}NumericFieldEnum, true>>;", edge.name));
    out.push(format!("        _min?: Partial<Record<{}NumericFieldEnum, true>>;", edge.name));
    out.push(format!("        _max?: Partial<Record<{}NumericFieldEnum, true>>;", edge.name));
    out.push(format!("        having?: {}HavingInput;", edge.name));
    out.push(format!(
        "        orderBy?: {}GroupByOrderByInput | {}GroupByOrderByInput[];",
        edge.name, edge.name
    ));
    out.push("        take?: number;".to_owned());
    out.push("        skip?: number;".to_owned());
    out.push("      }): Promise<Record<string, unknown>[]> =>".to_owned());
    out.push(format!(
        "        groupByRecords(db, \"{table}\", args as {{ by: string[]; where?: Record<string, unknown>; _count?: true | Record<string, boolean | undefined>; _sum?: Record<string, boolean | undefined>; _avg?: Record<string, boolean | undefined>; _min?: Record<string, boolean | undefined>; _max?: Record<string, boolean | undefined>; having?: Record<string, unknown>; orderBy?: Record<string, unknown> | Record<string, unknown>[]; take?: number; skip?: number }}),"
    ));
    out.push(format!(
        "      create: (data: {}CreateInput): Promise<{}> => create{}(db, data),",
        edge.name, edge.name, edge.name
    ));
    out.push(format!(
        "      createMany: <S extends {}Select | undefined = undefined, R extends Exclude<MutationReturn, \"BEFORE\"> | undefined = undefined>(args: {{",
        edge.name
    ));
    out.push(format!("        data: {}CreateInput[];", edge.name));
    out.push("        select?: S;".to_owned());
    out.push("        return?: R;".to_owned());
    out.push(format!(
        "      }}): Promise<ManyReturnResult<S, R, {}, {}GetPayload<S>>> =>",
        edge.name, edge.name
    ));
    out.push(format!(
        "        createManyVia(db, \"{table}\", args as {{ data: Record<string, unknown>[]; select?: Record<string, unknown>; return?: MutationReturn }}, (data) => create{}(db, data as {}CreateInput), true) as Promise<ManyReturnResult<S, R, {}, {}GetPayload<S>>>,",
        edge.name, edge.name, edge.name, edge.name
    ));
    out.push(format!(
        "      update: <S extends {}Select | undefined = undefined, R extends MutationReturn | undefined = undefined>(",
        edge.name
    ));
    out.push(format!(
        "        id: RecordId<\"{table}\"> | string, data: {}UpdateInput, opts?: {{ select?: S; return?: R }},",
        edge.name
    ));
    out.push(format!(
        "      ): Promise<SingleUpdateResult<S, R, {}, {}GetPayload<S>>> =>",
        edge.name, edge.name
    ));
    out.push(format!(
        "        updateOneRecord(db, \"{table}\", String(id), data as Record<string, unknown>, opts as {{ select?: Record<string, unknown>; return?: MutationReturn }} | undefined) as Promise<SingleUpdateResult<S, R, {}, {}GetPayload<S>>>,",
        edge.name, edge.name
    ));
    out.push(format!(
        "      updateMany: <S extends {}Select | undefined = undefined, R extends MutationReturn | undefined = undefined>(args: {{",
        edge.name
    ));
    out.push(format!("        where: {}WhereInput;", edge.name));
    out.push(format!("        data: {}UpdateInput;", edge.name));
    out.push("        select?: S;".to_owned());
    out.push("        return?: R;".to_owned());
    out.push(format!(
        "      }}): Promise<ManyReturnResult<S, R, {}, {}GetPayload<S>>> =>",
        edge.name, edge.name
    ));
    out.push(format!(
        "        updateManyRecords(db, \"{table}\", args as {{ where: Record<string, unknown>; data: Record<string, unknown>; select?: Record<string, unknown>; return?: MutationReturn }}) as Promise<ManyReturnResult<S, R, {}, {}GetPayload<S>>>,",
        edge.name, edge.name
    ));
    out.push(format!(
        "      delete: <S extends {}Select | undefined = undefined, R extends Exclude<MutationReturn, \"AFTER\"> | undefined = undefined>(",
        edge.name
    ));
    out.push(format!(
        "        id: RecordId<\"{table}\"> | string, opts?: {{ select?: S; return?: R }},"
    ));
    out.push(format!(
        "      ): Promise<SingleDeleteResult<S, R, {}, {}GetPayload<S>>> =>",
        edge.name, edge.name
    ));
    out.push(format!(
        "        deleteOneRecord(db, \"{table}\", String(id), opts as {{ select?: Record<string, unknown>; return?: MutationReturn }} | undefined) as Promise<SingleDeleteResult<S, R, {}, {}GetPayload<S>>>,",
        edge.name, edge.name
    ));
    out.push(format!(
        "      deleteMany: <S extends {}Select | undefined = undefined, R extends Exclude<MutationReturn, \"AFTER\"> | undefined = undefined>(args: {{",
        edge.name
    ));
    out.push(format!("        where: {}WhereInput;", edge.name));
    out.push("        select?: S;".to_owned());
    out.push("        return?: R;".to_owned());
    out.push(format!(
        "      }}): Promise<ManyReturnResult<S, R, {}, {}GetPayload<S>>> =>",
        edge.name, edge.name
    ));
    out.push(format!(
        "        deleteManyRecords(db, \"{table}\", args as {{ where: Record<string, unknown>; select?: Record<string, unknown>; return?: MutationReturn }}) as Promise<ManyReturnResult<S, R, {}, {}GetPayload<S>>>,",
        edge.name, edge.name
    ));
    out.push(format!(
        "      upsert: <S extends {}Select | undefined = undefined, R extends MutationReturn | undefined = undefined>(args: {{",
        edge.name
    ));
    out.push(format!("        where: {}WhereUniqueInput;", edge.name));
    out.push(format!("        create: {}CreateInput;", edge.name));
    out.push(format!("        update: {}UpdateInput;", edge.name));
    out.push("        select?: S;".to_owned());
    out.push("        return?: R;".to_owned());
    out.push(format!(
        "      }}): Promise<SingleUpsertResult<S, R, {}, {}GetPayload<S>>> =>",
        edge.name, edge.name
    ));
    out.push(format!(
        "        upsertRecord(db, \"{table}\", args as {{ where: Record<string, unknown>; create: Record<string, unknown>; update: Record<string, unknown>; select?: Record<string, unknown>; return?: MutationReturn }}, (data) => create{}(db, data as {}CreateInput)) as Promise<SingleUpsertResult<S, R, {}, {}GetPayload<S>>>,",
        edge.name, edge.name, edge.name, edge.name
    ));
    out.push("    },".to_owned());
}

fn client_key(name: &str) -> String {
    let mut chars = name.chars();
    chars
        .next()
        .map_or_else(String::new, |first| first.to_lowercase().collect::<String>() + chars.as_str())
}

fn query_fn_name(name: &str) -> String {
    if name.ends_with('s') { format!("query{name}") } else { format!("query{name}s") }
}

fn query_related_fn_name(name: &str) -> String {
    format!("{}Related", query_fn_name(name))
}

fn js_string_array(items: &[String]) -> String {
    if items.is_empty() {
        "[]".to_owned()
    } else {
        format!(
            "[{}]",
            items.iter().map(|item| format!("\"{item}\"")).collect::<Vec<_>>().join(", ")
        )
    }
}

fn fetch_field_names(model: &Model, naming: &NamingContext<'_>) -> Vec<String> {
    model
        .fields
        .iter()
        .filter(|field| !field.name.contains('.'))
        .filter(|field| field.is_link() || field.relation_name.is_some())
        .map(|field| naming.field_name(field))
        .collect()
}
